In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Social_Sector_Expenditure.csv",index_col=None,header=0,encoding='latin-1')

#  Data preprocessing

In [6]:
df #/Social_Sector_Expenditure

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16 (RE)
0,Andhra Pradesh,532,613,697,1073,1193,1470,1849,1884,2103,...,18654.0,24471.0,31440.0,30280.0,39130.0,45400.0,49440.0,53740,46150,52450
1,Arunachal Pradesh,,,,,,,78,102,113,...,843.0,953.0,1280.0,1770.0,1570.0,2160.0,1940.0,2550,4150,4060
2,Assam,171,176,215,339,382,467,597,681,727,...,5220.0,6056.0,6760.0,9160.0,10240.0,11190.0,12300.0,14510,28280,27810
3,Bihar,452,598,673,677,758,1231,1353,1431,1849,...,11127.0,13815.0,16340.0,17870.0,19370.0,24050.0,30740.0,34920,67080,56140
4,Chhattisgarh,,,,,,,,,,...,5707.0,6947.0,8870.0,11680.0,11820.0,14810.0,16970.0,21050,30350,37350
5,Goa,,,,,,,91,86,122,...,1010.0,1124.0,1460.0,1790.0,2090.0,2300.0,2500.0,2920,3800,4680
6,Gujarat,406,472,643,669,841,1046,1252,1537,1590,...,13104.0,14893.0,18180.0,23170.0,28590.0,30350.0,38060.0,41880,51980,57900
7,Haryana,137,173,235,242,281,369,360,488,650,...,5605.0,7343.0,9810.0,13360.0,13640.0,16270.0,18990.0,18100,26670,30790
8,Himachal Pradesh,106,113,128,139,156,223,251,322,398,...,3334.0,3736.0,4570.0,4910.0,6020.0,6000.0,7100.0,7890,9560,11320
9,Jammu & Kashmir,125,134,149,179,215,273,338,460,458,...,4348.0,5108.0,5610.0,6900.0,7430.0,8740.0,9120.0,9810,13540,14200
10,Jharkhand,,,,,,,,,,...,7392.0,7984.0,9870.0,10040.0,12300.0,10720.0,12030.0,11710,24530,27360
11,Karnataka,348,400,485,525,658,1010,1150,1361,1441,...,14407.0,17644.0,20440.0,25100.0,28690.0,32370.0,37830.0,41590,56740,57450
12,Kerala,391,424,441,557,618,918,942,976,1109,...,7189.0,9010.0,10860.0,12030.0,13620.0,18740.0,21650.0,23950,31400,36570
13,Madhya Pradesh,397,456,547,677,773,1083,1237,1527,1810,...,10658.0,12600.0,14690.0,17630.0,23450.0,27130.0,33370.0,35740,57530,59290
14,Maharashtra,754,847,1031,1282,1434,1968,2480,2603,2937,...,28276.0,29721.0,36500.0,47360.0,53830.0,61130.0,70030.0,78200,100320,110020
15,Manipur,41,44,47,61,65,80,118,111,151,...,1041.0,1179.0,1450.0,1540.0,1930.0,2020.0,2050.0,2110,4520,3350
16,Meghalaya,30,35,40,54,54,70,79,91,119,...,873.0,1039.0,1220.0,1400.0,1750.0,2340.0,2310.0,2720,6440,3710
17,Mizoram,,,,,,74,12,126,117,...,798.0,940.0,1150.0,1470.0,1600.0,1640.0,2120.0,2300,3190,2910
18,Nagaland,38,40,48,62,62,84,110,150,154,...,914.0,1053.0,1120.0,1170.0,1580.0,1610.0,1970.0,2150,3310,3810
19,Odisha,274,258,470,357,406,559,668,742,843,...,6127.0,8196.0,11090.0,12520.0,15240.0,18050.0,19660.0,24810,34970,37440
20,Punjab,252,280,292,354,388,681,369,595,929,...,4706.0,4991.0,6860.0,7110.0,8350.0,9970.0,12560.0,13080,17810,18510
21,Rajasthan,323,425,498,544,625,768,971,1439,1412,...,12580.0,14683.0,19430.0,21580.0,22790.0,27850.0,33700.0,41900,59940,67370
22,Sikkim,9,11,11,16,20,35,40,46,57,...,547.0,663.0,820.0,1010.0,1060.0,1450.0,1390.0,1690,2370,2010
23,Tamil Nadu,506,605,798,931,972,1444,1559,1735,1921,...,16921.0,19994.0,26890.0,29350.0,36490.0,41900.0,46750.0,55120,68280,70980
24,Telangana,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,46440,51130
25,Tripura,49,40,47,61,70,115,133,170,216,...,1206.0,1399.0,1680.0,2180.0,2160.0,2690.0,2870.0,3250,5970,7210
26,Uttar Pradesh,821,824,1015,1131,1333,1861,2075,2337,2919,...,24032.0,30006.0,39510.0,47250.0,50670.0,59720.0,67440.0,76560,102240,116170
27,Uttarakhand,,,,,,,,,,...,3226.0,3726.0,4190.0,5620.0,5950.0,7380.0,7970.0,9380,15340,15200
28,West Bengal,592,691,843,856,1115,1202,1500,1652,1852,...,13142.0,16192.0,19470.0,27700.0,30560.0,35610.0,40100.0,45580,59220,62630
29,Delhi,,,,,,,,,,...,5139.0,7353.0,8920.0,10510.0,10810.0,13210.0,14570.0,15430,17780,22230
30,Puducherry,,,,,,,,,,...,800.0,927.0,1060.0,1370.0,1560.0,1720.0,1410.0,1870,2330,2730

In [7]:
df.fillna(value=0,inplace=True)

In [8]:
df

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16 (RE)
0,Andhra Pradesh,532,613,697,1073,1193,1470,1849,1884,2103,...,18654.0,24471.0,31440.0,30280.0,39130.0,45400.0,49440.0,53740,46150,52450
1,Arunachal Pradesh,,,,,,,78,102,113,...,843.0,953.0,1280.0,1770.0,1570.0,2160.0,1940.0,2550,4150,4060
2,Assam,171,176,215,339,382,467,597,681,727,...,5220.0,6056.0,6760.0,9160.0,10240.0,11190.0,12300.0,14510,28280,27810
3,Bihar,452,598,673,677,758,1231,1353,1431,1849,...,11127.0,13815.0,16340.0,17870.0,19370.0,24050.0,30740.0,34920,67080,56140
4,Chhattisgarh,,,,,,,,,,...,5707.0,6947.0,8870.0,11680.0,11820.0,14810.0,16970.0,21050,30350,37350
5,Goa,,,,,,,91,86,122,...,1010.0,1124.0,1460.0,1790.0,2090.0,2300.0,2500.0,2920,3800,4680
6,Gujarat,406,472,643,669,841,1046,1252,1537,1590,...,13104.0,14893.0,18180.0,23170.0,28590.0,30350.0,38060.0,41880,51980,57900
7,Haryana,137,173,235,242,281,369,360,488,650,...,5605.0,7343.0,9810.0,13360.0,13640.0,16270.0,18990.0,18100,26670,30790
8,Himachal Pradesh,106,113,128,139,156,223,251,322,398,...,3334.0,3736.0,4570.0,4910.0,6020.0,6000.0,7100.0,7890,9560,11320
9,Jammu & Kashmir,125,134,149,179,215,273,338,460,458,...,4348.0,5108.0,5610.0,6900.0,7430.0,8740.0,9120.0,9810,13540,14200
10,Jharkhand,,,,,,,,,,...,7392.0,7984.0,9870.0,10040.0,12300.0,10720.0,12030.0,11710,24530,27360
11,Karnataka,348,400,485,525,658,1010,1150,1361,1441,...,14407.0,17644.0,20440.0,25100.0,28690.0,32370.0,37830.0,41590,56740,57450
12,Kerala,391,424,441,557,618,918,942,976,1109,...,7189.0,9010.0,10860.0,12030.0,13620.0,18740.0,21650.0,23950,31400,36570
13,Madhya Pradesh,397,456,547,677,773,1083,1237,1527,1810,...,10658.0,12600.0,14690.0,17630.0,23450.0,27130.0,33370.0,35740,57530,59290
14,Maharashtra,754,847,1031,1282,1434,1968,2480,2603,2937,...,28276.0,29721.0,36500.0,47360.0,53830.0,61130.0,70030.0,78200,100320,110020
15,Manipur,41,44,47,61,65,80,118,111,151,...,1041.0,1179.0,1450.0,1540.0,1930.0,2020.0,2050.0,2110,4520,3350
16,Meghalaya,30,35,40,54,54,70,79,91,119,...,873.0,1039.0,1220.0,1400.0,1750.0,2340.0,2310.0,2720,6440,3710
17,Mizoram,,,,,,74,12,126,117,...,798.0,940.0,1150.0,1470.0,1600.0,1640.0,2120.0,2300,3190,2910
18,Nagaland,38,40,48,62,62,84,110,150,154,...,914.0,1053.0,1120.0,1170.0,1580.0,1610.0,1970.0,2150,3310,3810
19,Odisha,274,258,470,357,406,559,668,742,843,...,6127.0,8196.0,11090.0,12520.0,15240.0,18050.0,19660.0,24810,34970,37440
20,Punjab,252,280,292,354,388,681,369,595,929,...,4706.0,4991.0,6860.0,7110.0,8350.0,9970.0,12560.0,13080,17810,18510
21,Rajasthan,323,425,498,544,625,768,971,1439,1412,...,12580.0,14683.0,19430.0,21580.0,22790.0,27850.0,33700.0,41900,59940,67370
22,Sikkim,9,11,11,16,20,35,40,46,57,...,547.0,663.0,820.0,1010.0,1060.0,1450.0,1390.0,1690,2370,2010
23,Tamil Nadu,506,605,798,931,972,1444,1559,1735,1921,...,16921.0,19994.0,26890.0,29350.0,36490.0,41900.0,46750.0,55120,68280,70980
24,Telangana,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,46440,51130
25,Tripura,49,40,47,61,70,115,133,170,216,...,1206.0,1399.0,1680.0,2180.0,2160.0,2690.0,2870.0,3250,5970,7210
26,Uttar Pradesh,821,824,1015,1131,1333,1861,2075,2337,2919,...,24032.0,30006.0,39510.0,47250.0,50670.0,59720.0,67440.0,76560,102240,116170
27,Uttarakhand,,,,,,,,,,...,3226.0,3726.0,4190.0,5620.0,5950.0,7380.0,7970.0,9380,15340,15200
28,West Bengal,592,691,843,856,1115,1202,1500,1652,1852,...,13142.0,16192.0,19470.0,27700.0,30560.0,35610.0,40100.0,45580,59220,62630
29,Delhi,,,,,,,,,,...,5139.0,7353.0,8920.0,10510.0,10810.0,13210.0,14570.0,15430,17780,22230
30,Puducherry,,,,,,,,,,...,800.0,927.0,1060.0,1370.0,1560.0,1720.0,1410.0,1870,2330,2730

In [9]:
df=df.replace('',0)

In [10]:
df

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16 (RE)
0,Andhra Pradesh,532,613,697,1073,1193,1470,1849,1884,2103,...,18654.0,24471.0,31440.0,30280.0,39130.0,45400.0,49440.0,53740,46150,52450
1,Arunachal Pradesh,0,0,0,0,0,0,78,102,113,...,843.0,953.0,1280.0,1770.0,1570.0,2160.0,1940.0,2550,4150,4060
2,Assam,171,176,215,339,382,467,597,681,727,...,5220.0,6056.0,6760.0,9160.0,10240.0,11190.0,12300.0,14510,28280,27810
3,Bihar,452,598,673,677,758,1231,1353,1431,1849,...,11127.0,13815.0,16340.0,17870.0,19370.0,24050.0,30740.0,34920,67080,56140
4,Chhattisgarh,0,0,0,0,0,0,0,0,0,...,5707.0,6947.0,8870.0,11680.0,11820.0,14810.0,16970.0,21050,30350,37350
5,Goa,0,0,0,0,0,0,91,86,122,...,1010.0,1124.0,1460.0,1790.0,2090.0,2300.0,2500.0,2920,3800,4680
6,Gujarat,406,472,643,669,841,1046,1252,1537,1590,...,13104.0,14893.0,18180.0,23170.0,28590.0,30350.0,38060.0,41880,51980,57900
7,Haryana,137,173,235,242,281,369,360,488,650,...,5605.0,7343.0,9810.0,13360.0,13640.0,16270.0,18990.0,18100,26670,30790
8,Himachal Pradesh,106,113,128,139,156,223,251,322,398,...,3334.0,3736.0,4570.0,4910.0,6020.0,6000.0,7100.0,7890,9560,11320
9,Jammu & Kashmir,125,134,149,179,215,273,338,460,458,...,4348.0,5108.0,5610.0,6900.0,7430.0,8740.0,9120.0,9810,13540,14200
10,Jharkhand,0,0,0,0,0,0,0,0,0,...,7392.0,7984.0,9870.0,10040.0,12300.0,10720.0,12030.0,11710,24530,27360
11,Karnataka,348,400,485,525,658,1010,1150,1361,1441,...,14407.0,17644.0,20440.0,25100.0,28690.0,32370.0,37830.0,41590,56740,57450
12,Kerala,391,424,441,557,618,918,942,976,1109,...,7189.0,9010.0,10860.0,12030.0,13620.0,18740.0,21650.0,23950,31400,36570
13,Madhya Pradesh,397,456,547,677,773,1083,1237,1527,1810,...,10658.0,12600.0,14690.0,17630.0,23450.0,27130.0,33370.0,35740,57530,59290
14,Maharashtra,754,847,1031,1282,1434,1968,2480,2603,2937,...,28276.0,29721.0,36500.0,47360.0,53830.0,61130.0,70030.0,78200,100320,110020
15,Manipur,41,44,47,61,65,80,118,111,151,...,1041.0,1179.0,1450.0,1540.0,1930.0,2020.0,2050.0,2110,4520,3350
16,Meghalaya,30,35,40,54,54,70,79,91,119,...,873.0,1039.0,1220.0,1400.0,1750.0,2340.0,2310.0,2720,6440,3710
17,Mizoram,0,0,0,0,0,74,12,126,117,...,798.0,940.0,1150.0,1470.0,1600.0,1640.0,2120.0,2300,3190,2910
18,Nagaland,38,40,48,62,62,84,110,150,154,...,914.0,1053.0,1120.0,1170.0,1580.0,1610.0,1970.0,2150,3310,3810
19,Odisha,274,258,470,357,406,559,668,742,843,...,6127.0,8196.0,11090.0,12520.0,15240.0,18050.0,19660.0,24810,34970,37440
20,Punjab,252,280,292,354,388,681,369,595,929,...,4706.0,4991.0,6860.0,7110.0,8350.0,9970.0,12560.0,13080,17810,18510
21,Rajasthan,323,425,498,544,625,768,971,1439,1412,...,12580.0,14683.0,19430.0,21580.0,22790.0,27850.0,33700.0,41900,59940,67370
22,Sikkim,9,11,11,16,20,35,40,46,57,...,547.0,663.0,820.0,1010.0,1060.0,1450.0,1390.0,1690,2370,2010
23,Tamil Nadu,506,605,798,931,972,1444,1559,1735,1921,...,16921.0,19994.0,26890.0,29350.0,36490.0,41900.0,46750.0,55120,68280,70980
24,Telangana,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,46440,51130
25,Tripura,49,40,47,61,70,115,133,170,216,...,1206.0,1399.0,1680.0,2180.0,2160.0,2690.0,2870.0,3250,5970,7210
26,Uttar Pradesh,821,824,1015,1131,1333,1861,2075,2337,2919,...,24032.0,30006.0,39510.0,47250.0,50670.0,59720.0,67440.0,76560,102240,116170
27,Uttarakhand,0,0,0,0,0,0,0,0,0,...,3226.0,3726.0,4190.0,5620.0,5950.0,7380.0,7970.0,9380,15340,15200
28,West Bengal,592,691,843,856,1115,1202,1500,1652,1852,...,13142.0,16192.0,19470.0,27700.0,30560.0,35610.0,40100.0,45580,59220,62630
29,Delhi,0,0,0,0,0,0,0,0,0,...,5139.0,7353.0,8920.0,10510.0,10810.0,13210.0,14570.0,15430,17780,22230
30,Puducherry,0,0,0,0,0,0,0,0,0,...,800.0,927.0,1060.0,1370.0,1560.0,1720.0,1410.0,1870,2330,2730

In [11]:
for i in df:
    df[i]=pd.to_numeric(df[i],errors='ignore')

In [12]:
df2=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Revenue_Expenditure.csv",index_col=None,header=0,encoding='latin-1')

In [13]:
df2 #Revenue_Expenditure

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
0,Andhra Pradesh,1161,1386,1507,2042,2463,2781,3245,3441,4246,...,41438.0,53984.0,61854.22,63447.93,78534.26,90415.36,102702.38,110374.49,98308.63,97424.78
1,Arunachal Pradesh,,,,,,,173,246,214,...,1897.0,2260.0,2871.68,3698.74,3744.24,4417.86,4786.24,5731.40,8522.80,9302.43
2,Assam,357,402,483,688,835,943,1149,1326,1435,...,11457.0,12744.0,14243.31,21232.18,22951.82,26528.56,29136.92,31971.81,52429.18,51562.85
3,Bihar,929,1167,1357,1432,1687,2098,2277,2619,3211,...,20585.0,23565.0,28511.57,32584.17,38215.92,46499.48,54466.14,62477.23,100254.89,91208.11
4,Chhattisgarh,,,,,,,,,,...,8802.0,10840.0,13793.70,17265.44,19355.75,22628.04,26971.84,32859.57,46665.43,53729.81
5,Goa,,,,,,,172,169,199,...,2468.0,2778.0,3425.41,4227.48,4783.79,5482.08,6061.34,6803.28,7953.96,9529.02
6,Gujarat,903,1039,1283,1426,1701,1972,2469,3093,3362,...,29232.0,33540.0,38741.45,48638.28,57440.00,59744.46,69658.49,75258.55,92597.89,101986.68
7,Haryana,401,486,567,623,761,854,967,1288,1443,...,16362.0,17527.0,20534.73,25257.38,28310.18,32014.89,38071.72,41887.10,54919.09,61869.62
8,Himachal Pradesh,188,212,263,284,344,411,464,609,768,...,7644.0,8292.0,9438.13,11151.01,13246.09,13897.97,16174.25,17352.48,20445.03,23487.69
9,Jammu & Kashmir,273,296,326,422,509,595,653,861,966,...,10067.0,11685.0,12446.86,15099.93,18466.81,22680.48,25117.22,27057.77,31050.59,34714.08
10,Jharkhand,,,,,,,,,,...,11234.0,13096.0,15479.21,17227.21,20242.58,20991.58,23397.83,23431.39,40073.33,43343.24
11,Karnataka,895,1002,1239,1417,1884,2098,2205,2667,3002,...,33435.0,37375.0,41659.29,47536.92,54033.85,65115.07,76293.26,89189.57,108747.62,115449.68
12,Kerala,668,755,783,992,1139,1445,1655,1781,2061,...,20825.0,24892.0,28223.88,31132.36,34664.81,46044.62,53488.74,60485.50,73852.31,85259.12
13,Madhya Pradesh,1016,1115,1328,1624,1734,2103,2532,3053,3618,...,22363.0,25601.0,29513.88,35896.90,45011.59,52693.71,62968.53,69869.76,98249.60,108834.92
14,Maharashtra,1917,2238,2628,3181,3880,4491,4979,5505,6541,...,61385.0,64780.0,75693.91,94915.97,106459.37,123554.19,138735.98,154902.42,194677.31,201987.90
15,Manipur,71,85,92,105,134,156,198,215,278,...,2415.0,2293.0,2622.27,3014.41,4077.99,5005.22,5316.53,5718.83,8990.13,7965.08
16,Meghalaya,60,74,85,100,117,135,156,190,225,...,1908.0,2254.0,2682.77,3182.38,4012.72,4834.81,4999.53,5551.59,9902.78,7621.48
17,Mizoram,,,,,,132,46,246,231,...,1717.0,1908.0,2313.80,2702.69,3400.44,4875.66,4508.91,4916.98,6268.51,6091.29
18,Nagaland,92,101,128,165,163,204,263,328,344,...,2222.0,2572.0,2889.53,3252.42,4187.82,4875.66,5601.39,5750.35,7605.56,8661.62
19,Odisha,541,574,825,783,897,1001,1248,1408,1659,...,15772.0,17723.0,24568.99,25291.59,29367.94,34660.23,38237.55,45617.75,60272.15,65838.99
20,Punjab,550,620,684,820,941,1163,1202,1634,1868,...,18544.0,23061.0,24568.99,27407.94,32897.18,33045.32,39457.94,41640.67,48982.74,52623.20
21,Rajasthan,688,823,955,1099,1303,1508,1867,2539,2571,...,24954.0,29128.0,34295.60,40132.20,44873.35,53653.31,63461.79,75509.59,100887.94,110804.85
22,Sikkim,30,32,36,49,59,78,81,99,113,...,1888.0,2349.0,2293.61,2738.05,2907.53,3230.14,3012.35,3457.96,4895.44,4258.51
23,Tamil Nadu,1152,1360,1576,1911,2210,2450,2776,3375,3763,...,38265.0,42975.0,53590.26,59375.35,72916.30,83838.04,97067.44,109824.67,136725.38,147297.35
24,Telangana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,79809.76,93600.21
25,Tripura,87,91,109,140,146,190,232,294,381,...,2483.0,2794.0,3129.45,4213.79,4359.34,4809.08,5212.88,5948.96,8303.07,9125.55
26,Uttar Pradesh,1716,1906,2364,2761,3292,3702,4349,5080,6257,...,55699.0,65223.0,75968.89,89373.60,107675.61,123885.17,140723.64,158146.87,191590.23,215756.18
27,Uttarakhand,,,,,,,,,,...,6477.0,7255.0,8395.36,10657.48,11621.08,12975.33,13960.22,16216.41,24352.48,25739.33
28,West Bengal,1115,1312,1622,1739,2151,2260,2698,3028,3475,...,34161.0,38314.0,51613.33,58499.87,64538.19,73326.37,82110.88,91797.27,106827.98,113100.22
29,Delhi,,,,,,,,,,...,7755.0,9771.0,11762.55,13900.88,14381.73,17964.86,20659.36,22366.52,26037.78,30402.09
30,Puducherry,,,,,,,,,,...,1927.0,2201.0,2570.47,3083.48,3540.17,3222.23,3051.19,4482.74,5055.22,5598.33

In [14]:
df2.fillna(value=0,inplace=True)

In [15]:
df2=df2.replace('',0)

In [16]:
for i in df2:
    df2[i]=pd.to_numeric(df2[i],errors='ignore')

In [17]:
df2

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
0,Andhra Pradesh,1161,1386,1507,2042,2463,2781,3245,3441,4246,...,41438.0,53984.0,61854.22,63447.93,78534.26,90415.36,102702.38,110374.49,98308.63,97424.78
1,Arunachal Pradesh,0,0,0,0,0,0,173,246,214,...,1897.0,2260.0,2871.68,3698.74,3744.24,4417.86,4786.24,5731.40,8522.80,9302.43
2,Assam,357,402,483,688,835,943,1149,1326,1435,...,11457.0,12744.0,14243.31,21232.18,22951.82,26528.56,29136.92,31971.81,52429.18,51562.85
3,Bihar,929,1167,1357,1432,1687,2098,2277,2619,3211,...,20585.0,23565.0,28511.57,32584.17,38215.92,46499.48,54466.14,62477.23,100254.89,91208.11
4,Chhattisgarh,0,0,0,0,0,0,0,0,0,...,8802.0,10840.0,13793.70,17265.44,19355.75,22628.04,26971.84,32859.57,46665.43,53729.81
5,Goa,0,0,0,0,0,0,172,169,199,...,2468.0,2778.0,3425.41,4227.48,4783.79,5482.08,6061.34,6803.28,7953.96,9529.02
6,Gujarat,903,1039,1283,1426,1701,1972,2469,3093,3362,...,29232.0,33540.0,38741.45,48638.28,57440.00,59744.46,69658.49,75258.55,92597.89,101986.68
7,Haryana,401,486,567,623,761,854,967,1288,1443,...,16362.0,17527.0,20534.73,25257.38,28310.18,32014.89,38071.72,41887.10,54919.09,61869.62
8,Himachal Pradesh,188,212,263,284,344,411,464,609,768,...,7644.0,8292.0,9438.13,11151.01,13246.09,13897.97,16174.25,17352.48,20445.03,23487.69
9,Jammu & Kashmir,273,296,326,422,509,595,653,861,966,...,10067.0,11685.0,12446.86,15099.93,18466.81,22680.48,25117.22,27057.77,31050.59,34714.08
10,Jharkhand,0,0,0,0,0,0,0,0,0,...,11234.0,13096.0,15479.21,17227.21,20242.58,20991.58,23397.83,23431.39,40073.33,43343.24
11,Karnataka,895,1002,1239,1417,1884,2098,2205,2667,3002,...,33435.0,37375.0,41659.29,47536.92,54033.85,65115.07,76293.26,89189.57,108747.62,115449.68
12,Kerala,668,755,783,992,1139,1445,1655,1781,2061,...,20825.0,24892.0,28223.88,31132.36,34664.81,46044.62,53488.74,60485.50,73852.31,85259.12
13,Madhya Pradesh,1016,1115,1328,1624,1734,2103,2532,3053,3618,...,22363.0,25601.0,29513.88,35896.90,45011.59,52693.71,62968.53,69869.76,98249.60,108834.92
14,Maharashtra,1917,2238,2628,3181,3880,4491,4979,5505,6541,...,61385.0,64780.0,75693.91,94915.97,106459.37,123554.19,138735.98,154902.42,194677.31,201987.90
15,Manipur,71,85,92,105,134,156,198,215,278,...,2415.0,2293.0,2622.27,3014.41,4077.99,5005.22,5316.53,5718.83,8990.13,7965.08
16,Meghalaya,60,74,85,100,117,135,156,190,225,...,1908.0,2254.0,2682.77,3182.38,4012.72,4834.81,4999.53,5551.59,9902.78,7621.48
17,Mizoram,0,0,0,0,0,132,46,246,231,...,1717.0,1908.0,2313.80,2702.69,3400.44,4875.66,4508.91,4916.98,6268.51,6091.29
18,Nagaland,92,101,128,165,163,204,263,328,344,...,2222.0,2572.0,2889.53,3252.42,4187.82,4875.66,5601.39,5750.35,7605.56,8661.62
19,Odisha,541,574,825,783,897,1001,1248,1408,1659,...,15772.0,17723.0,24568.99,25291.59,29367.94,34660.23,38237.55,45617.75,60272.15,65838.99
20,Punjab,550,620,684,820,941,1163,1202,1634,1868,...,18544.0,23061.0,24568.99,27407.94,32897.18,33045.32,39457.94,41640.67,48982.74,52623.20
21,Rajasthan,688,823,955,1099,1303,1508,1867,2539,2571,...,24954.0,29128.0,34295.60,40132.20,44873.35,53653.31,63461.79,75509.59,100887.94,110804.85
22,Sikkim,30,32,36,49,59,78,81,99,113,...,1888.0,2349.0,2293.61,2738.05,2907.53,3230.14,3012.35,3457.96,4895.44,4258.51
23,Tamil Nadu,1152,1360,1576,1911,2210,2450,2776,3375,3763,...,38265.0,42975.0,53590.26,59375.35,72916.30,83838.04,97067.44,109824.67,136725.38,147297.35
24,Telangana,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,79809.76,93600.21
25,Tripura,87,91,109,140,146,190,232,294,381,...,2483.0,2794.0,3129.45,4213.79,4359.34,4809.08,5212.88,5948.96,8303.07,9125.55
26,Uttar Pradesh,1716,1906,2364,2761,3292,3702,4349,5080,6257,...,55699.0,65223.0,75968.89,89373.60,107675.61,123885.17,140723.64,158146.87,191590.23,215756.18
27,Uttarakhand,0,0,0,0,0,0,0,0,0,...,6477.0,7255.0,8395.36,10657.48,11621.08,12975.33,13960.22,16216.41,24352.48,25739.33
28,West Bengal,1115,1312,1622,1739,2151,2260,2698,3028,3475,...,34161.0,38314.0,51613.33,58499.87,64538.19,73326.37,82110.88,91797.27,106827.98,113100.22
29,Delhi,0,0,0,0,0,0,0,0,0,...,7755.0,9771.0,11762.55,13900.88,14381.73,17964.86,20659.36,22366.52,26037.78,30402.09
30,Puducherry,0,0,0,0,0,0,0,0,0,...,1927.0,2201.0,2570.47,3083.48,3540.17,3222.23,3051.19,4482.74,5055.22,5598.33

In [18]:
df3=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Revenue_Deficits.csv",index_col=None,header=0,encoding='latin-1')

In [19]:
df3 #Revenue_Deficits

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16 (RE)
0,Andhra Pradesh,-104,-80,-132.6,88.6,169,7.3,189,-37,-33,...,-2807.0,-159.0,-1000.0,-1230.0,-2460.0,-3140.0,-1130.0,-340,14240,7300
1,Arunachal Pradesh,,,,,,,-39,-50,-93,...,-695.0,-743.0,-980.0,-600.0,-1680.0,-1080.0,-980.0,-90,1210,-2330
2,Assam,-165,36.8,43.9,137.2,135.8,5.6,-61,84,62.1,...,-2210.0,-2581.0,-3830.0,1350.0,-50.0,-930.0,-1550.0,-240,5090,-5500
3,Bihar,-59,7,37.7,-72.1,-106.7,-297.7,-346,-190,-277.5,...,-2498.0,-4645.0,-4470.0,-2940.0,-6320.0,-4820.0,-5100.0,-6440,4510,-11980
4,Chhattisgarh,,,,,,,,,,...,-2647.0,-3039.0,-1870.0,-890.0,-3360.0,-3240.0,-2610.0,810,-2380,-4230
5,Goa,,,,,,,1,7,-12,...,-141.0,-166.0,-100.0,130.0,-660.0,-300.0,220.0,350,-50,-410
6,Gujarat,-122,-120.3,-66.3,-139,-68.3,70,309,286,126.7,...,-1770.0,-2150.0,70.0,6970.0,5080.0,-3210.0,-5570.0,-4720,-6390,-7310
7,Haryana,-59,-50.5,-44.8,-75.9,-29.6,-106.1,-163,-17,1.9,...,-1590.0,-2224.0,2080.0,4260.0,2750.0,1460.0,4440.0,3880,9500,9560
8,Himachal Pradesh,-104,-21.8,-9.1,-32.7,-37.6,-107.8,-70,-41,69.8,...,-191.0,-850.0,130.0,800.0,540.0,-640.0,580.0,1640,1540,-50
9,Jammu & Kashmir,15,-2.3,1,46.5,70.9,-6.6,-42,107,63.9,...,-1914.0,-2216.0,-3360.0,-4450.0,-3770.0,-2100.0,-1100.0,-70,-3490,-3100
10,Jharkhand,,,,,,,,,,...,1090.0,1484.0,-630.0,-2610.0,140.0,-1430.0,-1370.0,-2710,-3830,-4680
11,Karnataka,-59,-164.3,-41.9,-72.9,143.6,84.7,-79,110,38.7,...,-4152.0,-3776.0,-1630.0,-1620.0,-4170.0,-4690.0,-1880.0,-350,-160,-910
12,Kerala,28,-96,-26.8,58.2,13.7,74.2,152,195,163.9,...,2638.0,3785.0,3710.0,5020.0,3670.0,8030.0,9350.0,11310,10260,7830
13,Madhya Pradesh,-118,-229.3,-187.8,-176.3,-79.1,-70.4,-35,59,145.8,...,-3332.0,-5088.0,-4060.0,-5500.0,-6840.0,-9910.0,-7460.0,-5880,-6370,-5590
14,Maharashtra,-121,-147.4,-210.1,-70.8,212,316.7,0.6,-74,240.8,...,-810.0,-14803.0,-5580.0,8010.0,590.0,2270.0,-4210.0,5080,13880,3760
15,Manipur,-41,-10,-20.3,-24.4,-37.6,-70.4,-50,-72,-65,...,-448.0,-1216.0,-1250.0,-860.0,-1350.0,-650.0,-1500.0,-1560,-970,-690
16,Meghalaya,-30,-8.1,-11.8,-24.6,-31.2,-48,-58,-66,-77.7,...,-235.0,-188.0,-130.0,-260.0,-250.0,180.0,-540.0,-720,-1220,-780
17,Mizoram,,,,,,1.5,-22,52,-43,...,-252.0,-131.0,-340.0,-260.0,30.0,-290.0,-30.0,150,950,-1080
18,Nagaland,-52,-7.8,-5.5,3.3,-37.6,-60.8,-34,-23,-41.2,...,-550.0,-424.0,-510.0,-470.0,-810.0,-710.0,-600.0,-750,-480,-230
19,Odisha,-81,-28,23,-0.4,74,60.1,20,75,107.8,...,-2261.0,-4244.0,-3420.0,-1140.0,-3910.0,-5610.0,-5700.0,-3330,-3380,-5100
20,Punjab,-18,-62.6,-102.5,-59.3,9.4,-7.3,-90,229,244.1,...,1749.0,3823.0,3860.0,5250.0,5290.0,6810.0,7410.0,6540,6240,6390
21,Rajasthan,-65,-34.3,-54.5,-44.7,75.9,2.2,60,356,218.5,...,-638.0,-1653.0,830.0,4750.0,-1050.0,-3360.0,-3450.0,1040,4220,-560
22,Sikkim,-7,-7.5,-12.8,-6.8,-18.7,-14.1,-32,-28,-36,...,-229.0,-351.0,-380.0,-520.0,-140.0,-440.0,-780.0,-870,-1280,-540
23,Tamil Nadu,-128,-81.7,-101.9,-51.7,-17.2,-188.6,-103,283,274.2,...,-2648.0,-4545.0,-1450.0,3530.0,2730.0,-1360.0,-1760.0,1790,3540,4620
24,Telangana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,-280,-530
25,Tripura,-36,-5.8,-15.2,-4.9,-36.5,-41.2,-42,-20,-15.1,...,-851.0,-904.0,-950.0,-1410.0,-810.0,-1670.0,-1840.0,-1700,-2360,-3400
26,Uttar Pradesh,-183,-353.4,-192.4,105.8,147.3,-174.6,177,-252,604.5,...,-4901.0,-3449.0,-1860.0,-7050.0,-3510.0,-6980.0,-5180.0,-10070,-32410,-34120
27,Uttarakhand,,,,,,,,,,...,-896.0,-637.0,-240.0,1170.0,10.0,-720.0,-1790.0,-1100,-2160,-40
28,West Bengal,23,87.8,242.4,206.2,371.9,-82.9,188,115,137.2,...,8333.0,8147.0,14710.0,21580.0,17270.0,14570.0,13820.0,18920,10360,0
29,Delhi,,,,,,,,,,...,-4438.0,-5142.0,-4590.0,-6550.0,-10640.0,-4430.0,-4900.0,-5610,-6100,-8160
30,Puducherry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,43.0,65.0,110.0,240.0,340.0,450.0,-90.0,180,-90,0

In [20]:
df3.fillna(value=0,inplace=True)

In [21]:
df3=df3.replace('',0)

In [22]:
for i in df3:
    df3[i]=pd.to_numeric(df3[i],errors='ignore')

In [23]:
df3

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16 (RE)
0,Andhra Pradesh,-104,-80.0,-132.6,88.6,169.0,7.3,189.0,-37,-33.0,...,-2807.0,-159.0,-1000.0,-1230.0,-2460.0,-3140.0,-1130.0,-340,14240,7300
1,Arunachal Pradesh,0,0.0,0.0,0.0,0.0,0.0,-39.0,-50,-93.0,...,-695.0,-743.0,-980.0,-600.0,-1680.0,-1080.0,-980.0,-90,1210,-2330
2,Assam,-165,36.8,43.9,137.2,135.8,5.6,-61.0,84,62.1,...,-2210.0,-2581.0,-3830.0,1350.0,-50.0,-930.0,-1550.0,-240,5090,-5500
3,Bihar,-59,7.0,37.7,-72.1,-106.7,-297.7,-346.0,-190,-277.5,...,-2498.0,-4645.0,-4470.0,-2940.0,-6320.0,-4820.0,-5100.0,-6440,4510,-11980
4,Chhattisgarh,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,-2647.0,-3039.0,-1870.0,-890.0,-3360.0,-3240.0,-2610.0,810,-2380,-4230
5,Goa,0,0.0,0.0,0.0,0.0,0.0,1.0,7,-12.0,...,-141.0,-166.0,-100.0,130.0,-660.0,-300.0,220.0,350,-50,-410
6,Gujarat,-122,-120.3,-66.3,-139.0,-68.3,70.0,309.0,286,126.7,...,-1770.0,-2150.0,70.0,6970.0,5080.0,-3210.0,-5570.0,-4720,-6390,-7310
7,Haryana,-59,-50.5,-44.8,-75.9,-29.6,-106.1,-163.0,-17,1.9,...,-1590.0,-2224.0,2080.0,4260.0,2750.0,1460.0,4440.0,3880,9500,9560
8,Himachal Pradesh,-104,-21.8,-9.1,-32.7,-37.6,-107.8,-70.0,-41,69.8,...,-191.0,-850.0,130.0,800.0,540.0,-640.0,580.0,1640,1540,-50
9,Jammu & Kashmir,15,-2.3,1.0,46.5,70.9,-6.6,-42.0,107,63.9,...,-1914.0,-2216.0,-3360.0,-4450.0,-3770.0,-2100.0,-1100.0,-70,-3490,-3100
10,Jharkhand,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,1090.0,1484.0,-630.0,-2610.0,140.0,-1430.0,-1370.0,-2710,-3830,-4680
11,Karnataka,-59,-164.3,-41.9,-72.9,143.6,84.7,-79.0,110,38.7,...,-4152.0,-3776.0,-1630.0,-1620.0,-4170.0,-4690.0,-1880.0,-350,-160,-910
12,Kerala,28,-96.0,-26.8,58.2,13.7,74.2,152.0,195,163.9,...,2638.0,3785.0,3710.0,5020.0,3670.0,8030.0,9350.0,11310,10260,7830
13,Madhya Pradesh,-118,-229.3,-187.8,-176.3,-79.1,-70.4,-35.0,59,145.8,...,-3332.0,-5088.0,-4060.0,-5500.0,-6840.0,-9910.0,-7460.0,-5880,-6370,-5590
14,Maharashtra,-121,-147.4,-210.1,-70.8,212.0,316.7,0.6,-74,240.8,...,-810.0,-14803.0,-5580.0,8010.0,590.0,2270.0,-4210.0,5080,13880,3760
15,Manipur,-41,-10.0,-20.3,-24.4,-37.6,-70.4,-50.0,-72,-65.0,...,-448.0,-1216.0,-1250.0,-860.0,-1350.0,-650.0,-1500.0,-1560,-970,-690
16,Meghalaya,-30,-8.1,-11.8,-24.6,-31.2,-48.0,-58.0,-66,-77.7,...,-235.0,-188.0,-130.0,-260.0,-250.0,180.0,-540.0,-720,-1220,-780
17,Mizoram,0,0.0,0.0,0.0,0.0,1.5,-22.0,52,-43.0,...,-252.0,-131.0,-340.0,-260.0,30.0,-290.0,-30.0,150,950,-1080
18,Nagaland,-52,-7.8,-5.5,3.3,-37.6,-60.8,-34.0,-23,-41.2,...,-550.0,-424.0,-510.0,-470.0,-810.0,-710.0,-600.0,-750,-480,-230
19,Odisha,-81,-28.0,23.0,-0.4,74.0,60.1,20.0,75,107.8,...,-2261.0,-4244.0,-3420.0,-1140.0,-3910.0,-5610.0,-5700.0,-3330,-3380,-5100
20,Punjab,-18,-62.6,-102.5,-59.3,9.4,-7.3,-90.0,229,244.1,...,1749.0,3823.0,3860.0,5250.0,5290.0,6810.0,7410.0,6540,6240,6390
21,Rajasthan,-65,-34.3,-54.5,-44.7,75.9,2.2,60.0,356,218.5,...,-638.0,-1653.0,830.0,4750.0,-1050.0,-3360.0,-3450.0,1040,4220,-560
22,Sikkim,-7,-7.5,-12.8,-6.8,-18.7,-14.1,-32.0,-28,-36.0,...,-229.0,-351.0,-380.0,-520.0,-140.0,-440.0,-780.0,-870,-1280,-540
23,Tamil Nadu,-128,-81.7,-101.9,-51.7,-17.2,-188.6,-103.0,283,274.2,...,-2648.0,-4545.0,-1450.0,3530.0,2730.0,-1360.0,-1760.0,1790,3540,4620
24,Telangana,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,-280,-530
25,Tripura,-36,-5.8,-15.2,-4.9,-36.5,-41.2,-42.0,-20,-15.1,...,-851.0,-904.0,-950.0,-1410.0,-810.0,-1670.0,-1840.0,-1700,-2360,-3400
26,Uttar Pradesh,-183,-353.4,-192.4,105.8,147.3,-174.6,177.0,-252,604.5,...,-4901.0,-3449.0,-1860.0,-7050.0,-3510.0,-6980.0,-5180.0,-10070,-32410,-34120
27,Uttarakhand,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,-896.0,-637.0,-240.0,1170.0,10.0,-720.0,-1790.0,-1100,-2160,-40
28,West Bengal,23,87.8,242.4,206.2,371.9,-82.9,188.0,115,137.2,...,8333.0,8147.0,14710.0,21580.0,17270.0,14570.0,13820.0,18920,10360,0
29,Delhi,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,-4438.0,-5142.0,-4590.0,-6550.0,-10640.0,-4430.0,-4900.0,-5610,-6100,-8160
30,Puducherry,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,...,43.0,65.0,110.0,240.0,340.0,450.0,-90.0,180,-90,0

In [24]:
df3.dtypes

State            object
1980-81           int64
1981-82         float64
1982-83         float64
1983-84         float64
1984-85         float64
1985-86         float64
1986-87         float64
1987-88           int64
1988-89         float64
1989-90         float64
1990-91         float64
1991-92         float64
1992-93         float64
1993-94         float64
1994-95         float64
1995-96         float64
1996-97         float64
1997-98         float64
1998-99         float64
1999-00         float64
2000-01         float64
2001-02          object
2002-03           int64
2003-04           int64
2004-05           int64
2005-06         float64
2006-07         float64
2007-08         float64
2008-09         float64
2009-10         float64
2010-11         float64
2011-12         float64
2012-13         float64
2013-14           int64
2014-15           int64
2015-16 (RE)      int64
dtype: object

In [25]:
df3.to_csv('file3.csv')

In [26]:
df.to_csv('file4.csv')

In [27]:
df4=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Own_Tax_Revenues.csv",index_col=None,header=0,encoding='latin-1')

In [28]:
df4 #Own_Tax_Revenues

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16
0,Andhra Pradesh,582,703,808,965,1174,1439,1559,1819,2122,...,23930.0,28790.0,33360.0,35180.0,45140.0,53280.0,59880.0,64120,38480,44420
1,Arunachal Pradesh,,,,,,,2,2,2,...,80.0,100.0,140.0,170.0,210.0,320.0,320.0,430,490,510
2,Assam,66,90,108,136,189,235,245,249,279,...,3480.0,3360.0,4150.0,4990.0,5930.0,7640.0,8250.0,8990,10750,12890
3,Bihar,277,338,382,442,464,576,659,761,831,...,4030.0,5090.0,6170.0,8090.0,9870.0,12610.0,16250.0,19960,25660,30880
4,Chhattisgarh,,,,,,,,,,...,5050.0,5620.0,6590.0,7120.0,9010.0,10710.0,13030.0,14340,18130,20090
5,Goa,,,,,,,61,52,62,...,1290.0,1360.0,1690.0,1760.0,2140.0,2550.0,2940.0,3580,4080,4290
6,Gujarat,531,661,763,879,980,1075,1264,1526,1871,...,18470.0,21890.0,23560.0,26740.0,36340.0,44250.0,53900.0,56370,62070,68420
7,Haryana,234,291,337,366,406,502,566,664,795,...,10930.0,11620.0,11660.0,13220.0,16790.0,20400.0,23560.0,25570,29600,33250
8,Himachal Pradesh,34,42,48,54,61,74,92,103,118,...,1660.0,1960.0,2240.0,2570.0,3640.0,4110.0,4630.0,5120,5700,6340
9,Jammu & Kashmir,38,60,62,71,79,104,118,123,138,...,1900.0,2300.0,2690.0,3070.0,3480.0,4750.0,5830.0,6270,6440,8010
10,Jharkhand,,,,,,,,,,...,3130.0,3550.0,5080.0,5560.0,5970.0,6950.0,8220.0,9380,13310,14700
11,Karnataka,475,607,674,760,909,1076,1206,1415,1699,...,23300.0,25990.0,27650.0,30580.0,38470.0,46480.0,53750.0,62600,68550,76450
12,Kerala,337,374,438,487,622,731,814,925,1066,...,11940.0,13670.0,15990.0,17630.0,21720.0,25720.0,30080.0,32000,38280,45430
13,Madhya Pradesh,386,476,558,643,713,831,974,1115,1338,...,10470.0,12020.0,13610.0,17270.0,21420.0,26970.0,30580.0,33550,39190,43450
14,Maharashtra,1130,1384,1648,1823,1966,2377,2792,3219,3823,...,40100.0,47530.0,52030.0,59110.0,75030.0,87610.0,103450.0,108600,118960,130580
15,Manipur,3,4,4,5,6,7,9,12,12,...,120.0,150.0,170.0,200.0,270.0,370.0,330.0,470,590,670
16,Meghalaya,5,6,7,10,12,15,18,20,28,...,300.0,320.0,370.0,440.0,570.0,700.0,850.0,950,1210,1040
17,Mizoram,,,,,,2,,4,2,...,70.0,80.0,90.0,110.0,130.0,180.0,220.0,230,270,330
18,Nagaland,4,6,7,10,9,10,13,15,16,...,120.0,130.0,160.0,180.0,230.0,300.0,340.0,330,360,430
19,Odisha,132,160,174,201,228,286,338,387,443,...,6070.0,6860.0,8000.0,8980.0,11190.0,13440.0,15030.0,16890,19270,21280
20,Punjab,349,432,491,544,567,670,803,916,1041,...,9020.0,9900.0,11150.0,12040.0,16830.0,18840.0,22590.0,24080,28560,29350
21,Rajasthan,230,312,390,441,487,566,656,773,893,...,11610.0,13280.0,14940.0,16410.0,20760.0,25380.0,30500.0,33480,39790,47100
22,Sikkim,3,3,3,4,5,6,7,11,11,...,170.0,200.0,180.0,220.0,280.0,290.0,440.0,520,510,560
23,Tamil Nadu,639,842,1012,1145,1298,1548,1757,1762,1994,...,27770.0,29620.0,33680.0,36550.0,47780.0,59520.0,71250.0,73720,85770,96080
24,Telangana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,35380,46500
25,Tripura,4,5,6,8,8,10,12,14,18,...,340.0,370.0,440.0,530.0,620.0,860.0,1000.0,1070,1240,1320
26,Uttar Pradesh,645,823,929,992,1140,1291,1529,1989,2066,...,23000.0,24960.0,28660.0,33880.0,41350.0,52610.0,58100.0,66580,75970,91920
27,Uttarakhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2510.0,2740.0,3040.0,3560.0,4410.0,5620.0,6410.0,7360,8200,9460
28,West Bengal,514,616,638,769,937,1124,1219,1449,1735,...,11700.0,13130.0,14420.0,16900.0,21130.0,24940.0,32810.0,35830,40060,46500
29,Delhi,,,,,,,,,,...,10160.0,11780.0,12180.0,13450.0,16480.0,19970.0,23430.0,25920,27670,34660
30,Puducherry,,,,,,,,,,...,570.0,650.0,730.0,870.0,1500.0,1590.0,1920.0,1900,2030,2340

In [29]:
df4.fillna(value=0,inplace=True)

In [30]:
df4=df4.replace('',0)

In [31]:
for i in df4:
    df4[i]=pd.to_numeric(df4[i],errors='ignore')

In [32]:
df4.dtypes

State       object
1980-81      int64
1981-82      int64
1982-83      int64
1983-84      int64
1984-85      int64
1985-86      int64
1986-87      int64
1987-88      int64
1988-89      int64
1989-90      int64
1990-91    float64
1991-92    float64
1992-93    float64
1993-94    float64
1994-95    float64
1995-96    float64
1996-97    float64
1997-98    float64
1998-99    float64
1999-00    float64
2000-01    float64
2001-02    float64
2002-03    float64
2003-04    float64
2004-05    float64
2005-06    float64
2006-07    float64
2007-08    float64
2008-09    float64
2009-10    float64
2010-11    float64
2011-12    float64
2012-13    float64
2013-14      int64
2014-15      int64
2015-16      int64
dtype: object

In [33]:
df4.to_csv('Own_Tax_Revenues.csv')

In [34]:
df5=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Nominal_GSDP_Series.csv",index_col=None,header=0,encoding='latin-1')

In [35]:
df5 #Nominal_GSP_Series

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,Unnamed: 37
0,Andhra Pradesh,8191.0,10041.0,10844.0,12564.0,13576.0,15266.0,16404.0,19608.0,24732.0,...,212361,237383,273327,319864,3.792296e+05,4.109608e+05,4.684940e+05,5.329220e+05,6.033762e+05,NaN
1,Arunachal Pradesh,107.0,142.0,166.0,189.0,221.0,269.0,305.0,330.0,387.0,...,4810,5687,7474,9021,1.106269e+04,1.254665e+04,1.460736e+04,1.638923e+04,1.947253e+04,NaN
2,Assam,2516.0,3228.0,3657.0,4347.0,5113.0,5673.0,6176.0,7001.0,7600.0,...,71076,81074,95975,112688,1.431749e+05,1.568642e+05,1.777452e+05,1.980980e+05,NaN,NaN
3,Bihar,7353.0,8562.0,9635.0,10945.0,13004.0,14295.0,16261.0,17638.0,21181.0,...,113680,142279,162923,203555,2.471440e+05,2.823679e+05,3.171013e+05,3.739199e+05,4.135032e+05,NaN
4,Chhattisgarh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80255,96972,99364,119420,1.580738e+05,1.775113e+05,2.067857e+05,2.363178e+05,NaN,NaN
5,Goa,398.0,436.0,519.0,549.0,666.0,655.0,771.0,856.0,978.0,...,19565,25414,29126,33605,4.225274e+04,3.864729e+04,4.224345e+04,4.554755e+04,NaN,NaN
6,Gujarat,7427.0,9253.0,9887.0,12681.0,13311.0,13988.0,16174.0,16339.0,22349.0,...,329285,367912,431262,521519,6.156061e+05,7.244958e+05,8.076232e+05,8.959267e+05,NaN,NaN
7,Haryana,3386.0,3911.0,4485.0,4890.0,5382.0,6552.0,6889.0,7739.0,10015.0,...,151596,182522,223600,260621,3.007556e+05,3.504066e+05,3.957477e+05,4.418643e+05,NaN,NaN
8,Himachal Pradesh,794.0,925.0,987.0,1127.0,1139.0,1372.0,1517.0,1722.0,2157.0,...,33963,41483,48189,57452,7.271983e+04,8.281978e+04,9.476416e+04,1.043688e+05,NaN,NaN
9,Jammu & Kashmir,1186.0,1361.0,1561.0,1782.0,2021.0,2256.0,2620.0,2524.0,3065.0,...,37099,42315,48385,58073,7.794498e+04,8.653733e+04,9.740031e+04,1.026805e+05,NaN,NaN
10,Jharkhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,83950,87794,100621,127281,1.509176e+05,1.747237e+05,1.885666e+05,2.171072e+05,2.419550e+05,NaN
11,Karnataka,6210.0,7169.0,8012.0,9610.0,10831.0,11575.0,13271.0,15158.0,17709.0,...,270629,310312,337559,410703,6.037776e+05,6.922241e+05,8.181672e+05,9.200614e+05,1.040148e+06,NaN
12,Kerala,4286.0,4610.0,5373.0,6272.0,6977.0,7520.0,8536.0,9578.0,10673.0,...,175141,202783,231999,263773,3.640479e+05,4.123130e+05,4.650398e+05,5.267744e+05,NaN,NaN
13,Madhya Pradesh,7788.0,8564.0,9822.0,11471.0,11871.0,13905.0,14513.0,18397.0,21663.0,...,161479,197276,227557,263396,3.155609e+05,3.809262e+05,4.357899e+05,4.845376e+05,5.650534e+05,NaN
14,Maharashtra,16631.0,18738.0,20315.0,23457.0,25558.0,29616.0,32009.0,37754.0,45160.0,...,684817,753969,855751,1049150,1.272967e+06,1.448466e+06,1.647506e+06,1.792122e+06,NaN,NaN
15,Manipur,218.0,265.0,285.0,337.0,382.0,418.0,479.0,604.0,680.0,...,6783,7399,8254,9137,1.291461e+04,1.374779e+04,1.619843e+04,1.804276e+04,NaN,NaN
16,Meghalaya,200.0,230.0,256.0,298.0,343.0,393.0,447.0,534.0,589.0,...,9735,11617,12709,14583,1.991775e+04,2.187202e+04,2.293824e+04,2.406499e+04,2.730451e+04,NaN
17,Mizoram,68.0,78.0,87.0,106.0,135.0,181.0,214.0,286.0,288.0,...,3816,4577,5260,6388,7.258690e+03,8.361930e+03,1.029337e+04,1.155933e+04,NaN,NaN
18,Nagaland,119.0,147.0,180.0,209.0,243.0,273.0,308.0,395.0,477.0,...,8075,9436,10527,11759,1.183912e+04,1.361877e+04,1.661185e+04,1.841424e+04,NaN,NaN
19,Odisha,3708.0,4162.0,4448.0,5708.0,5694.0,6823.0,7427.0,7614.0,9613.0,...,129274,148491,162946,197530,2.252835e+05,2.552726e+05,2.772707e+05,3.098072e+05,3.323291e+05,NaN
20,Punjab,5025.0,5954.0,6602.0,7326.0,8354.0,9506.0,10429.0,12255.0,14088.0,...,152245,174039,197500,226204,2.666283e+05,2.977338e+05,3.347143e+05,3.680109e+05,NaN,NaN
21,Rajasthan,4637.0,5461.0,6246.0,7863.0,7936.0,8797.0,9957.0,10925.0,14555.0,...,194822,230949,265825,338348,4.364653e+05,4.940038e+05,5.497006e+05,6.121945e+05,NaN,NaN
22,Sikkim,52.0,59.0,70.0,80.0,102.0,122.0,145.0,167.0,185.0,...,2506,3229,6133,7412,1.116510e+04,1.233842e+04,1.386190e+04,1.520933e+04,1.663678e+04,NaN
23,Tamil Nadu,8081.0,9712.0,10025.0,11646.0,13658.0,15648.0,17513.0,20693.0,23199.0,...,350819,401336,479733,584896,7.514851e+05,8.554809e+05,9.710899e+05,1.092564e+06,1.212668e+06,NaN
24,Telangana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,152452,189382,203508,263898,3.617007e+05,4.041048e+05,4.601715e+05,5.220011e+05,5.831172e+05,NaN
25,Tripura,286.0,339.0,386.0,426.0,474.0,524.0,580.0,668.0,853.0,...,11797,13573,15403,17868,1.920841e+04,2.166320e+04,2.559283e+04,2.966662e+04,NaN,NaN
26,Uttar Pradesh,15554.0,16887.0,19724.0,21896.0,24211.0,27748.0,30657.0,34352.0,41102.0,...,383026,444685,523394,600286,7.240486e+05,8.229030e+05,9.441457e+05,1.043371e+06,1.153795e+06,NaN
27,Uttarakhand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45856,56025,70730,83969,1.155235e+05,1.318352e+05,1.498166e+05,1.619853e+05,1.840913e+05,NaN
28,West Bengal,10345.0,11575.0,13049.0,15302.0,17676.0,19033.0,20803.0,25078.0,27107.0,...,299483,341942,398880,460959,5.283160e+05,6.033110e+05,7.065610e+05,8.008680e+05,NaN,NaN
29,Delhi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,157947,189533,217619,252753,3.432604e+05,3.910714e+05,4.468068e+05,4.944603e+05,5.587453e+05,NaN
30,Puducherry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9251,10050,12304,13092,1.681801e+04,1.887545e+04,2.187012e+04,2.408857e+04,2.653346e+04,NaN

In [36]:
df5.fillna(value=0,inplace=True)

In [37]:
df5=df5.replace('',0)

In [38]:
for i in df4:
    df4[i]=pd.to_numeric(df4[i],errors='ignore')

In [39]:
df5

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,Unnamed: 37
0,Andhra Pradesh,8191.0,10041.0,10844.0,12564.0,13576.0,15266.0,16404.0,19608.0,24732.0,...,212361,237383,273327,319864,3.792296e+05,4.109608e+05,4.684940e+05,5.329220e+05,6.033762e+05,0.0
1,Arunachal Pradesh,107.0,142.0,166.0,189.0,221.0,269.0,305.0,330.0,387.0,...,4810,5687,7474,9021,1.106269e+04,1.254665e+04,1.460736e+04,1.638923e+04,1.947253e+04,0.0
2,Assam,2516.0,3228.0,3657.0,4347.0,5113.0,5673.0,6176.0,7001.0,7600.0,...,71076,81074,95975,112688,1.431749e+05,1.568642e+05,1.777452e+05,1.980980e+05,0.000000e+00,0.0
3,Bihar,7353.0,8562.0,9635.0,10945.0,13004.0,14295.0,16261.0,17638.0,21181.0,...,113680,142279,162923,203555,2.471440e+05,2.823679e+05,3.171013e+05,3.739199e+05,4.135032e+05,0.0
4,Chhattisgarh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,80255,96972,99364,119420,1.580738e+05,1.775113e+05,2.067857e+05,2.363178e+05,0.000000e+00,0.0
5,Goa,398.0,436.0,519.0,549.0,666.0,655.0,771.0,856.0,978.0,...,19565,25414,29126,33605,4.225274e+04,3.864729e+04,4.224345e+04,4.554755e+04,0.000000e+00,0.0
6,Gujarat,7427.0,9253.0,9887.0,12681.0,13311.0,13988.0,16174.0,16339.0,22349.0,...,329285,367912,431262,521519,6.156061e+05,7.244958e+05,8.076232e+05,8.959267e+05,0.000000e+00,0.0
7,Haryana,3386.0,3911.0,4485.0,4890.0,5382.0,6552.0,6889.0,7739.0,10015.0,...,151596,182522,223600,260621,3.007556e+05,3.504066e+05,3.957477e+05,4.418643e+05,0.000000e+00,0.0
8,Himachal Pradesh,794.0,925.0,987.0,1127.0,1139.0,1372.0,1517.0,1722.0,2157.0,...,33963,41483,48189,57452,7.271983e+04,8.281978e+04,9.476416e+04,1.043688e+05,0.000000e+00,0.0
9,Jammu & Kashmir,1186.0,1361.0,1561.0,1782.0,2021.0,2256.0,2620.0,2524.0,3065.0,...,37099,42315,48385,58073,7.794498e+04,8.653733e+04,9.740031e+04,1.026805e+05,0.000000e+00,0.0
10,Jharkhand,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,83950,87794,100621,127281,1.509176e+05,1.747237e+05,1.885666e+05,2.171072e+05,2.419550e+05,0.0
11,Karnataka,6210.0,7169.0,8012.0,9610.0,10831.0,11575.0,13271.0,15158.0,17709.0,...,270629,310312,337559,410703,6.037776e+05,6.922241e+05,8.181672e+05,9.200614e+05,1.040148e+06,0.0
12,Kerala,4286.0,4610.0,5373.0,6272.0,6977.0,7520.0,8536.0,9578.0,10673.0,...,175141,202783,231999,263773,3.640479e+05,4.123130e+05,4.650398e+05,5.267744e+05,0.000000e+00,0.0
13,Madhya Pradesh,7788.0,8564.0,9822.0,11471.0,11871.0,13905.0,14513.0,18397.0,21663.0,...,161479,197276,227557,263396,3.155609e+05,3.809262e+05,4.357899e+05,4.845376e+05,5.650534e+05,0.0
14,Maharashtra,16631.0,18738.0,20315.0,23457.0,25558.0,29616.0,32009.0,37754.0,45160.0,...,684817,753969,855751,1049150,1.272967e+06,1.448466e+06,1.647506e+06,1.792122e+06,0.000000e+00,0.0
15,Manipur,218.0,265.0,285.0,337.0,382.0,418.0,479.0,604.0,680.0,...,6783,7399,8254,9137,1.291461e+04,1.374779e+04,1.619843e+04,1.804276e+04,0.000000e+00,0.0
16,Meghalaya,200.0,230.0,256.0,298.0,343.0,393.0,447.0,534.0,589.0,...,9735,11617,12709,14583,1.991775e+04,2.187202e+04,2.293824e+04,2.406499e+04,2.730451e+04,0.0
17,Mizoram,68.0,78.0,87.0,106.0,135.0,181.0,214.0,286.0,288.0,...,3816,4577,5260,6388,7.258690e+03,8.361930e+03,1.029337e+04,1.155933e+04,0.000000e+00,0.0
18,Nagaland,119.0,147.0,180.0,209.0,243.0,273.0,308.0,395.0,477.0,...,8075,9436,10527,11759,1.183912e+04,1.361877e+04,1.661185e+04,1.841424e+04,0.000000e+00,0.0
19,Odisha,3708.0,4162.0,4448.0,5708.0,5694.0,6823.0,7427.0,7614.0,9613.0,...,129274,148491,162946,197530,2.252835e+05,2.552726e+05,2.772707e+05,3.098072e+05,3.323291e+05,0.0
20,Punjab,5025.0,5954.0,6602.0,7326.0,8354.0,9506.0,10429.0,12255.0,14088.0,...,152245,174039,197500,226204,2.666283e+05,2.977338e+05,3.347143e+05,3.680109e+05,0.000000e+00,0.0
21,Rajasthan,4637.0,5461.0,6246.0,7863.0,7936.0,8797.0,9957.0,10925.0,14555.0,...,194822,230949,265825,338348,4.364653e+05,4.940038e+05,5.497006e+05,6.121945e+05,0.000000e+00,0.0
22,Sikkim,52.0,59.0,70.0,80.0,102.0,122.0,145.0,167.0,185.0,...,2506,3229,6133,7412,1.116510e+04,1.233842e+04,1.386190e+04,1.520933e+04,1.663678e+04,0.0
23,Tamil Nadu,8081.0,9712.0,10025.0,11646.0,13658.0,15648.0,17513.0,20693.0,23199.0,...,350819,401336,479733,584896,7.514851e+05,8.554809e+05,9.710899e+05,1.092564e+06,1.212668e+06,0.0
24,Telangana,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,152452,189382,203508,263898,3.617007e+05,4.041048e+05,4.601715e+05,5.220011e+05,5.831172e+05,0.0
25,Tripura,286.0,339.0,386.0,426.0,474.0,524.0,580.0,668.0,853.0,...,11797,13573,15403,17868,1.920841e+04,2.166320e+04,2.559283e+04,2.966662e+04,0.000000e+00,0.0
26,Uttar Pradesh,15554.0,16887.0,19724.0,21896.0,24211.0,27748.0,30657.0,34352.0,41102.0,...,383026,444685,523394,600286,7.240486e+05,8.229030e+05,9.441457e+05,1.043371e+06,1.153795e+06,0.0
27,Uttarakhand,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,45856,56025,70730,83969,1.155235e+05,1.318352e+05,1.498166e+05,1.619853e+05,1.840913e+05,0.0
28,West Bengal,10345.0,11575.0,13049.0,15302.0,17676.0,19033.0,20803.0,25078.0,27107.0,...,299483,341942,398880,460959,5.283160e+05,6.033110e+05,7.065610e+05,8.008680e+05,0.000000e+00,0.0
29,Delhi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,157947,189533,217619,252753,3.432604e+05,3.910714e+05,4.468068e+05,4.944603e+05,5.587453e+05,0.0
30,Puducherry,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9251,10050,12304,13092,1.681801e+04,1.887545e+04,2.187012e+04,2.408857e+04,2.653346e+04,0.0

In [40]:
df5.to_csv('Nominal_GSDP_Series.csv')

In [41]:
df6=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Gross_Fiscal_Deficits.csv",index_col=None,header=0,encoding='latin-1')

In [42]:
df6 #Gross_Fiscal_Deficits

,Year,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
0,Andhra Pradesh,222.1,243.7,172.4,493,591.4,435,804,568,673,...,5640.0,8790.0,12410.0,14010.0,11800.0,15400.0,17510.0,18040,20320,17580
1,Arunachal Pradesh,,,,,,,23,38,1,...,-110.0,-20.0,330.0,500.0,-10.0,990.0,230.0,1610,3560,510
2,Assam,-27.4,171.7,200.1,327.2,366.6,154,243,421,303,...,-710.0,-790.0,-1410.0,4040.0,1990.0,1650.0,1520.0,3780,16260,4680
3,Bihar,335.8,409.1,434.7,328,395.9,326,461,825,535,...,3020.0,1710.0,2510.0,5270.0,3970.0,5910.0,6550.0,8350,32820,13580
4,Chhattisgarh,,,,,,,,,,...,-30.0,130.0,1030.0,1760.0,-410.0,800.0,2660.0,5060,5770,6840
5,Goa,,,,,,,61,72,64,...,490.0,540.0,810.0,1240.0,570.0,880.0,1150.0,1350,1740,2710
6,Gujarat,246.5,253.9,376.6,397.6,520.2,514,900,976,735,...,5650.0,4770.0,10440.0,15150.0,15070.0,11030.0,16490.0,18420,18380,22050
7,Haryana,112,101.6,188.6,133.7,234.8,230,170,216,289,...,-1180.0,1260.0,6560.0,10090.0,7260.0,7150.0,10360.0,8310,15630,16420
8,Himachal Pradesh,-34.9,56.6,74.1,57.9,79.5,35,89,129,254,...,920.0,550.0,2280.0,2780.0,1830.0,1630.0,2980.0,4010,3830,3280
9,Jammu & Kashmir,144.5,135.9,142,198.3,248.2,247,244,417,410,...,1460.0,2610.0,2330.0,2230.0,2370.0,3690.0,4220.0,4550,6630,6630
10,Jharkhand,,,,,,,,,,...,5260.0,6220.0,3750.0,1780.0,4840.0,1930.0,3400.0,2220,4910,5160
11,Karnataka,225.9,118,279.9,287.7,563.3,550,514,518,497,...,4690.0,5330.0,8730.0,10870.0,10690.0,12300.0,14510.0,17090,19030,20220
12,Kerala,179.8,61.7,122.9,299.3,232.3,323,440,448,412,...,3820.0,6100.0,6350.0,7870.0,7730.0,12810.0,15000.0,16940,16000,17700
13,Madhya Pradesh,337.2,237.5,290.5,366.4,494.2,516,561,725,871,...,2750.0,2780.0,4430.0,6200.0,5270.0,5760.0,9420.0,9880,13570,16750
14,Maharashtra,463.3,488.5,551.5,739.7,1050.5,1234,1065,1014,1277,...,11550.0,-2820.0,14000.0,26160.0,18860.0,19970.0,13740.0,26020,37250,30730
15,Manipur,-6.7,27.1,17.4,26.2,14.5,-9,32,17,33,...,480.0,-100.0,220.0,730.0,570.0,1050.0,0.0,-270,930,580
16,Meghalaya,-7.7,16.5,15.1,10,2,-8,5,1.5,10,...,80.0,210.0,440.0,230.0,340.0,1070.0,400.0,380,530,820
17,Mizoram,,,,,,41,-22,102,11,...,190.0,390.0,90.0,310.0,650.0,210.0,580.0,750,2000,110
18,Nagaland,-26.3,20.1,29.5,41,-4.6,-12,30,60,48,...,160.0,400.0,340.0,520.0,310.0,540.0,650.0,460,850,1160
19,Odisha,134.1,141.8,212.2,191.6,328.4,326,372,506,550,...,-820.0,-1320.0,330.0,2270.0,660.0,-620.0,0.0,4630,9140,10400
20,Punjab,159.8,178.3,182.8,262.1,479.2,566,343,968,833,...,4380.0,4600.0,6690.0,6170.0,7140.0,8490.0,9350.0,8790,10400,11900
21,Rajasthan,206.7,326.5,274.9,297.5,362.7,343,467,903,736,...,3970.0,3410.0,6970.0,10300.0,4130.0,3630.0,8530.0,15190,23160,20610
22,Sikkim,5.6,4.8,-1.8,6.9,-2.8,12,1,9,11,...,100.0,60.0,230.0,170.0,320.0,180.0,70.0,50,450,520
23,Tamil Nadu,210.4,212.5,326.1,363.6,397.7,365,454,660,654,...,3960.0,3690.0,8550.0,11810.0,16650.0,17270.0,16520.0,20580,27350,31830
24,Telangana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,17400,16970
25,Tripura,-9.1,24.8,17.1,34.9,12.4,15,15,62,84,...,-130.0,20.0,270.0,-70.0,250.0,-260.0,-340.0,-50,1320,1940
26,Uttar Pradesh,551.4,452,581.7,1082.3,1493.6,1058,1410,1014,1802,...,9620.0,13790.0,20510.0,18690.0,17250.0,15430.0,19240.0,23680,28380,31560
27,Uttarakhand,,,,,,,,,,...,890.0,1740.0,1840.0,2780.0,1840.0,1760.0,1600.0,2650,3970,4100
28,West Bengal,289.2,380.1,497.8,413.9,339.7,259,587,551,579,...,11430.0,11400.0,13560.0,24950.0,19530.0,17700.0,19150.0,25350,23880,15980
29,Delhi,,,,,,,,,,...,410.0,2040.0,2820.0,3550.0,-730.0,2550.0,2280.0,3940,350,420
30,Puducherry,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,400.0,330.0,370.0,580.0,710.0,820.0,220.0,540,550,610

In [43]:
df6.fillna(value=0,inplace=True)

In [44]:
df6=df6.replace('',0)

In [45]:
for i in df6:
    df6[i]=pd.to_numeric(df6[i],errors='ignore')

In [46]:
df6

,Year,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
0,Andhra Pradesh,222.1,243.7,172.4,493.0,591.4,435,804,568.0,673,...,5640.0,8790.0,12410.0,14010.0,11800.0,15400.0,17510.0,18040,20320,17580
1,Arunachal Pradesh,0.0,0.0,0.0,0.0,0.0,0,23,38.0,1,...,-110.0,-20.0,330.0,500.0,-10.0,990.0,230.0,1610,3560,510
2,Assam,-27.4,171.7,200.1,327.2,366.6,154,243,421.0,303,...,-710.0,-790.0,-1410.0,4040.0,1990.0,1650.0,1520.0,3780,16260,4680
3,Bihar,335.8,409.1,434.7,328.0,395.9,326,461,825.0,535,...,3020.0,1710.0,2510.0,5270.0,3970.0,5910.0,6550.0,8350,32820,13580
4,Chhattisgarh,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,...,-30.0,130.0,1030.0,1760.0,-410.0,800.0,2660.0,5060,5770,6840
5,Goa,0.0,0.0,0.0,0.0,0.0,0,61,72.0,64,...,490.0,540.0,810.0,1240.0,570.0,880.0,1150.0,1350,1740,2710
6,Gujarat,246.5,253.9,376.6,397.6,520.2,514,900,976.0,735,...,5650.0,4770.0,10440.0,15150.0,15070.0,11030.0,16490.0,18420,18380,22050
7,Haryana,112.0,101.6,188.6,133.7,234.8,230,170,216.0,289,...,-1180.0,1260.0,6560.0,10090.0,7260.0,7150.0,10360.0,8310,15630,16420
8,Himachal Pradesh,-34.9,56.6,74.1,57.9,79.5,35,89,129.0,254,...,920.0,550.0,2280.0,2780.0,1830.0,1630.0,2980.0,4010,3830,3280
9,Jammu & Kashmir,144.5,135.9,142.0,198.3,248.2,247,244,417.0,410,...,1460.0,2610.0,2330.0,2230.0,2370.0,3690.0,4220.0,4550,6630,6630
10,Jharkhand,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,...,5260.0,6220.0,3750.0,1780.0,4840.0,1930.0,3400.0,2220,4910,5160
11,Karnataka,225.9,118.0,279.9,287.7,563.3,550,514,518.0,497,...,4690.0,5330.0,8730.0,10870.0,10690.0,12300.0,14510.0,17090,19030,20220
12,Kerala,179.8,61.7,122.9,299.3,232.3,323,440,448.0,412,...,3820.0,6100.0,6350.0,7870.0,7730.0,12810.0,15000.0,16940,16000,17700
13,Madhya Pradesh,337.2,237.5,290.5,366.4,494.2,516,561,725.0,871,...,2750.0,2780.0,4430.0,6200.0,5270.0,5760.0,9420.0,9880,13570,16750
14,Maharashtra,463.3,488.5,551.5,739.7,1050.5,1234,1065,1014.0,1277,...,11550.0,-2820.0,14000.0,26160.0,18860.0,19970.0,13740.0,26020,37250,30730
15,Manipur,-6.7,27.1,17.4,26.2,14.5,-9,32,17.0,33,...,480.0,-100.0,220.0,730.0,570.0,1050.0,0.0,-270,930,580
16,Meghalaya,-7.7,16.5,15.1,10.0,2.0,-8,5,1.5,10,...,80.0,210.0,440.0,230.0,340.0,1070.0,400.0,380,530,820
17,Mizoram,0.0,0.0,0.0,0.0,0.0,41,-22,102.0,11,...,190.0,390.0,90.0,310.0,650.0,210.0,580.0,750,2000,110
18,Nagaland,-26.3,20.1,29.5,41.0,-4.6,-12,30,60.0,48,...,160.0,400.0,340.0,520.0,310.0,540.0,650.0,460,850,1160
19,Odisha,134.1,141.8,212.2,191.6,328.4,326,372,506.0,550,...,-820.0,-1320.0,330.0,2270.0,660.0,-620.0,0.0,4630,9140,10400
20,Punjab,159.8,178.3,182.8,262.1,479.2,566,343,968.0,833,...,4380.0,4600.0,6690.0,6170.0,7140.0,8490.0,9350.0,8790,10400,11900
21,Rajasthan,206.7,326.5,274.9,297.5,362.7,343,467,903.0,736,...,3970.0,3410.0,6970.0,10300.0,4130.0,3630.0,8530.0,15190,23160,20610
22,Sikkim,5.6,4.8,-1.8,6.9,-2.8,12,1,9.0,11,...,100.0,60.0,230.0,170.0,320.0,180.0,70.0,50,450,520
23,Tamil Nadu,210.4,212.5,326.1,363.6,397.7,365,454,660.0,654,...,3960.0,3690.0,8550.0,11810.0,16650.0,17270.0,16520.0,20580,27350,31830
24,Telangana,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,17400,16970
25,Tripura,-9.1,24.8,17.1,34.9,12.4,15,15,62.0,84,...,-130.0,20.0,270.0,-70.0,250.0,-260.0,-340.0,-50,1320,1940
26,Uttar Pradesh,551.4,452.0,581.7,1082.3,1493.6,1058,1410,1014.0,1802,...,9620.0,13790.0,20510.0,18690.0,17250.0,15430.0,19240.0,23680,28380,31560
27,Uttarakhand,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,...,890.0,1740.0,1840.0,2780.0,1840.0,1760.0,1600.0,2650,3970,4100
28,West Bengal,289.2,380.1,497.8,413.9,339.7,259,587,551.0,579,...,11430.0,11400.0,13560.0,24950.0,19530.0,17700.0,19150.0,25350,23880,15980
29,Delhi,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,...,410.0,2040.0,2820.0,3550.0,-730.0,2550.0,2280.0,3940,350,420
30,Puducherry,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0,...,400.0,330.0,370.0,580.0,710.0,820.0,220.0,540,550,610

In [47]:
df6.to_csv('Gross_Fiscal_Deficits.csv')

In [48]:
df7=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Capital_Expenditure.csv",index_col=None,header=0,encoding='latin-1')

In [49]:
df7#/Capital_Expenditure

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
0,Andhra Pradesh,449,445,427,546,656,633,824,853,977,...,15210.0,20892.0,18949.67,21626.86,22101.38,25466.19,26738.54,26254.78,12758.83,14624.21
1,Arunachal Pradesh,,,,,,,78,102,111,...,889.0,809.0,1400.91,1537.88,1834.88,2247.31,1567.32,2050.23,2959.71,3410.48
2,Assam,401,215,208,254,330,264,437,469,420,...,2028.0,2406.0,3242.55,3736.12,2995.15,3740.37,4610.72,5206.59,12550.78,12039.32
3,Bihar,862,704,583,711,721,868,1083,1295,1113,...,6551.0,8008.0,8669.68,10211.86,12488.60,13680.55,14740.43,17927.94,31932.00,29477.21
4,Chhattisgarh,,,,,,,,,,...,3188.0,4189.0,3920.27,4293.28,4208.93,6092.65,7847.41,6582.37,9313.92,12080.89
5,Goa,,,,,,,83,90,85,...,708.0,781.0,1092.02,1296.97,1445.11,1471.49,1285.11,1346.22,2177.45,3573.75
6,Gujarat,539,526,666,752,762,653,853,996,1011,...,9968.0,9142.0,13155.97,11696.95,14166.61,19669.73,28622.83,29462.03,32892.36,35532.05
7,Haryana,207,211,350,338,359,461,542,375,436,...,3276.0,4553.0,5833.44,7304.55,6124.05,7736.54,8440.20,7041.55,8853.34,9805.18
8,Himachal Pradesh,150,84,90,101,134,177,183,196,216,...,2447.0,2322.0,3054.22,2879.91,2885.19,3430.54,4540.34,3918.70,4449.58,4850.93
9,Jammu & Kashmir,154,252,178,198,238,294,336,408,439,...,3806.0,5361.0,6303.03,7418.63,7102.11,7175.75,6660.81,4850.93,11420.62,11205.44
10,Jharkhand,,,,,,,,,,...,4492.0,5264.0,5162.26,5485.56,6259.46,5015.49,7001.99,6632.35,10766.22,12149.71
11,Karnataka,407,406,500,586,732,796,864,770,776,...,10649.0,10656.0,12379.53,15426.59,17900.24,20641.09,20307.91,21459.13,24087.82,25084.75
12,Kerala,188,331,213,329,433,523,507,470,460,...,2335.0,3801.0,4329.62,4701.12,6100.45,7744.52,8543.52,8884.39,9095.40,14018.62
13,Madhya Pradesh,573,562,610,700,788,813,818,879,978,...,7854.0,9664.0,10516.38,14135.55,15043.59,27965.25,20528.79,19894.40,25139.97,27137.15
14,Maharashtra,696,850,957,1063,1183,1241,1433,1425,1561,...,14456.0,15460.0,23374.57,22515.13,23696.05,25174.18,25466.44,31927.40,33255.32,38038.19
15,Manipur,88,43,44,53,89,91,101,104,115,...,1211.0,1427.0,1781.50,1711.42,2036.88,1857.42,1676.67,1454.09,2187.54,1687.33
16,Meghalaya,42,27,32,40,44,53,73,74,94,...,413.0,517.0,749.94,650.98,757.47,1110.25,1123.87,1259.42,1990.39,1961.77
17,Mizoram,,,,,,46,8,60,56,...,578.0,651.0,554.74,826.33,739.06,762.45,826.59,718.95,1254.71,1485.24
18,Nagaland,73,31,37,50,39,69,81,107,114,...,863.0,991.0,1059.93,1267.68,1388.22,1572.81,1592.75,1476.81,1635.84,1920.58
19,Odisha,336,240,367,214,384,410,482,582,602,...,3574.0,5121.0,5482.74,5249.05,6683.37,7444.87,9018.07,10513.17,15854.91,18648.78
20,Punjab,267,376,438,614,785,800,627,990,798,...,7753.0,3458.0,4216.72,3900.01,4162.85,3765.00,5049.34,6015.70,7448.21,9190.66
21,Rajasthan,432,537,464,487,535,609,691,845,845,...,6902.0,8630.0,8672.64,8617.61,8829.97,11718.77,17802.12,18591.49,24923.69,26908.54
22,Sikkim,13,13,11,18,18,26,34,40,51,...,366.0,471.0,688.30,771.79,530.05,713.59,918.57,1011.08,1820.85,1267.22
23,Tamil Nadu,534,646,716,841,740,859,836,821,854,...,12882.0,12773.0,14132.83,13354.98,17965.44,25627.23,24328.46,24367.71,24698.71,35041.23
24,Telangana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,20148.21,21458.98
25,Tripura,56,33,36,47,57,69,68,98,112,...,819.0,1041.0,1381.59,1543.72,1264.99,1628.67,1814.61,1876.42,4096.38,5823.37
26,Uttar Pradesh,952,1036,1127,1355,1894,1629,1876,1821,1822,...,19284.0,22081.0,28429.22,31741.70,26910.22,29827.14,32996.57,42573.18,70712.59,76931.14
27,Uttarakhand,,,,,,,,,,...,2039.0,2720.0,2493.43,2639.66,2388.89,3257.03,5256.19,5306.82,7103.32,6154.31
28,West Bengal,437,527,451,441,588,714,810,913,804,...,7042.0,8330.0,9319.79,9634.16,8423.98,10504.51,13246.62,16716.12,22819.48,25273.78
29,Delhi,,,,,,,,,,...,5211.0,8389.0,8598.75,11025.04,11142.59,8437.57,9199.45,11685.08,8752.22,10726.91
30,Puducherry,,,,,,,,,,...,460.0,387.0,386.13,502.35,520.81,533.78,504.98,567.59,862.77,832.67

In [50]:
df7.fillna(value=0,inplace=True)

In [51]:
df7=df7.replace('',0)

In [52]:
for i in df7:
    df7[i]=pd.to_numeric(df7[i],errors='ignore')

In [53]:
df7

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
0,Andhra Pradesh,449,445,427,546,656,633,824,853,977,...,15210.0,20892.0,18949.67,21626.86,22101.38,25466.19,26738.54,26254.78,12758.83,14624.21
1,Arunachal Pradesh,0,0,0,0,0,0,78,102,111,...,889.0,809.0,1400.91,1537.88,1834.88,2247.31,1567.32,2050.23,2959.71,3410.48
2,Assam,401,215,208,254,330,264,437,469,420,...,2028.0,2406.0,3242.55,3736.12,2995.15,3740.37,4610.72,5206.59,12550.78,12039.32
3,Bihar,862,704,583,711,721,868,1083,1295,1113,...,6551.0,8008.0,8669.68,10211.86,12488.60,13680.55,14740.43,17927.94,31932.00,29477.21
4,Chhattisgarh,0,0,0,0,0,0,0,0,0,...,3188.0,4189.0,3920.27,4293.28,4208.93,6092.65,7847.41,6582.37,9313.92,12080.89
5,Goa,0,0,0,0,0,0,83,90,85,...,708.0,781.0,1092.02,1296.97,1445.11,1471.49,1285.11,1346.22,2177.45,3573.75
6,Gujarat,539,526,666,752,762,653,853,996,1011,...,9968.0,9142.0,13155.97,11696.95,14166.61,19669.73,28622.83,29462.03,32892.36,35532.05
7,Haryana,207,211,350,338,359,461,542,375,436,...,3276.0,4553.0,5833.44,7304.55,6124.05,7736.54,8440.20,7041.55,8853.34,9805.18
8,Himachal Pradesh,150,84,90,101,134,177,183,196,216,...,2447.0,2322.0,3054.22,2879.91,2885.19,3430.54,4540.34,3918.70,4449.58,4850.93
9,Jammu & Kashmir,154,252,178,198,238,294,336,408,439,...,3806.0,5361.0,6303.03,7418.63,7102.11,7175.75,6660.81,4850.93,11420.62,11205.44
10,Jharkhand,0,0,0,0,0,0,0,0,0,...,4492.0,5264.0,5162.26,5485.56,6259.46,5015.49,7001.99,6632.35,10766.22,12149.71
11,Karnataka,407,406,500,586,732,796,864,770,776,...,10649.0,10656.0,12379.53,15426.59,17900.24,20641.09,20307.91,21459.13,24087.82,25084.75
12,Kerala,188,331,213,329,433,523,507,470,460,...,2335.0,3801.0,4329.62,4701.12,6100.45,7744.52,8543.52,8884.39,9095.40,14018.62
13,Madhya Pradesh,573,562,610,700,788,813,818,879,978,...,7854.0,9664.0,10516.38,14135.55,15043.59,27965.25,20528.79,19894.40,25139.97,27137.15
14,Maharashtra,696,850,957,1063,1183,1241,1433,1425,1561,...,14456.0,15460.0,23374.57,22515.13,23696.05,25174.18,25466.44,31927.40,33255.32,38038.19
15,Manipur,88,43,44,53,89,91,101,104,115,...,1211.0,1427.0,1781.50,1711.42,2036.88,1857.42,1676.67,1454.09,2187.54,1687.33
16,Meghalaya,42,27,32,40,44,53,73,74,94,...,413.0,517.0,749.94,650.98,757.47,1110.25,1123.87,1259.42,1990.39,1961.77
17,Mizoram,0,0,0,0,0,46,8,60,56,...,578.0,651.0,554.74,826.33,739.06,762.45,826.59,718.95,1254.71,1485.24
18,Nagaland,73,31,37,50,39,69,81,107,114,...,863.0,991.0,1059.93,1267.68,1388.22,1572.81,1592.75,1476.81,1635.84,1920.58
19,Odisha,336,240,367,214,384,410,482,582,602,...,3574.0,5121.0,5482.74,5249.05,6683.37,7444.87,9018.07,10513.17,15854.91,18648.78
20,Punjab,267,376,438,614,785,800,627,990,798,...,7753.0,3458.0,4216.72,3900.01,4162.85,3765.00,5049.34,6015.70,7448.21,9190.66
21,Rajasthan,432,537,464,487,535,609,691,845,845,...,6902.0,8630.0,8672.64,8617.61,8829.97,11718.77,17802.12,18591.49,24923.69,26908.54
22,Sikkim,13,13,11,18,18,26,34,40,51,...,366.0,471.0,688.30,771.79,530.05,713.59,918.57,1011.08,1820.85,1267.22
23,Tamil Nadu,534,646,716,841,740,859,836,821,854,...,12882.0,12773.0,14132.83,13354.98,17965.44,25627.23,24328.46,24367.71,24698.71,35041.23
24,Telangana,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,20148.21,21458.98
25,Tripura,56,33,36,47,57,69,68,98,112,...,819.0,1041.0,1381.59,1543.72,1264.99,1628.67,1814.61,1876.42,4096.38,5823.37
26,Uttar Pradesh,952,1036,1127,1355,1894,1629,1876,1821,1822,...,19284.0,22081.0,28429.22,31741.70,26910.22,29827.14,32996.57,42573.18,70712.59,76931.14
27,Uttarakhand,0,0,0,0,0,0,0,0,0,...,2039.0,2720.0,2493.43,2639.66,2388.89,3257.03,5256.19,5306.82,7103.32,6154.31
28,West Bengal,437,527,451,441,588,714,810,913,804,...,7042.0,8330.0,9319.79,9634.16,8423.98,10504.51,13246.62,16716.12,22819.48,25273.78
29,Delhi,0,0,0,0,0,0,0,0,0,...,5211.0,8389.0,8598.75,11025.04,11142.59,8437.57,9199.45,11685.08,8752.22,10726.91
30,Puducherry,0,0,0,0,0,0,0,0,0,...,460.0,387.0,386.13,502.35,520.81,533.78,504.98,567.59,862.77,832.67

In [54]:
df7.to_csv('Capital_Expenditure.csv')

In [55]:
df8=pd.read_csv("C:/Users/lenovo/Downloads/State wise Finances/Aggregate_Expenditure.csv",index_col=None,header=0,encoding='latin-1')

In [56]:
df8.fillna(value=0,inplace=True)#Aggregate_Expenditure

In [57]:
df8=df8.replace('',0)

In [58]:
for i in df8:
    df8[i]=pd.to_numeric(df8[i],errors='ignore')

In [59]:
df8.dtypes

State            object
1980-81           int64
1981-82           int64
1982-83           int64
1983-84           int64
1984-85           int64
1985-86           int64
1986-87           int64
1987-88           int64
1988-89           int64
1989-90           int64
1990-91           int64
1991-92           int64
1992-93           int64
1993-94           int64
1994-95           int64
1995-96           int64
1996-97           int64
1997-98           int64
1998-99           int64
1999-00           int64
2000-01           int64
2001-02           int64
2002-03           int64
2003-04           int64
2004-05           int64
2005-06           int64
2006-07           int64
2007-08           int64
2008-09         float64
2009-10         float64
2010-11         float64
2011-12         float64
2012-13         float64
2013-14         float64
2014-15 (RE)    float64
2015-16 (BE)    float64
dtype: object

In [60]:
df8

,State,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
0,Andhra Pradesh,1610,1831,1933,2588,3119,3413,4068,4294,5223,...,56648,74875,80803.89,85074.79,100635.64,115881.55,129440.92,136629.27,111067.46,112048.99
1,Arunachal Pradesh,0,0,0,0,0,0,251,348,326,...,2786,3068,4272.59,5236.62,5579.12,6665.17,6353.56,7781.63,11482.51,12712.91
2,Assam,758,618,691,942,1165,1207,1586,1794,1855,...,13485,15150,17485.86,24968.30,25946.97,30268.93,33747.64,37178.40,64979.96,63602.17
3,Bihar,1791,1871,1940,2144,2408,2966,3360,3914,4324,...,27136,31573,37181.25,42796.03,50704.52,60180.03,69206.57,80405.17,132186.89,120685.32
4,Chhattisgarh,0,0,0,0,0,0,0,0,0,...,11991,15029,17713.97,21558.72,23564.68,28720.69,34819.25,39441.94,55979.35,65810.70
5,Goa,0,0,0,0,0,0,255,258,284,...,3176,3559,4517.43,5524.45,6228.90,6953.57,7346.45,8149.50,10131.41,13102.77
6,Gujarat,1442,1565,1949,2178,2463,2625,3323,4089,4374,...,39200,42681,51897.42,60335.23,71606.61,79414.19,98281.32,104720.58,125490.25,137518.73
7,Haryana,607,696,917,960,1120,1315,1509,1663,1879,...,19638,22079,26368.17,32561.93,34434.23,39751.43,46511.92,48928.65,63772.43,71674.80
8,Himachal Pradesh,338,297,353,385,479,588,648,805,985,...,10091,10614,12492.35,14030.92,16131.28,17328.51,20714.59,21271.18,24894.61,28338.62
9,Jammu & Kashmir,428,548,504,620,747,889,989,1269,1404,...,13873,17046,18749.89,22518.56,25568.92,29856.23,31778.03,31908.70,42471.21,45919.52
10,Jharkhand,0,0,0,0,0,0,0,0,0,...,15726,18360,20641.47,22712.77,26502.04,26007.07,30399.82,30063.74,50839.55,55492.95
11,Karnataka,1302,1409,1739,2002,2615,2894,3069,3437,3778,...,44085,48031,54038.82,62963.51,71934.09,85756.16,96601.17,110648.70,132835.44,140534.43
12,Kerala,855,1086,996,1322,1572,1969,2162,2251,2521,...,23159,28692,32553.50,35833.48,40765.26,53789.14,62032.26,69369.89,82947.71,99277.74
13,Madhya Pradesh,1590,1677,1938,2324,2522,2916,3349,3932,4596,...,30217,35265,40030.26,50032.45,60055.18,80658.96,83497.32,89764.16,123389.57,135972.07
14,Maharashtra,2613,3088,3585,4244,5063,5732,6412,6929,8102,...,75841,80240,99068.48,117431.10,130155.42,148728.37,164202.42,186829.82,227932.63,240026.09
15,Manipur,159,128,137,158,223,247,299,319,393,...,3626,3720,4403.77,4725.83,6114.87,6862.64,6993.20,7172.92,11177.67,9652.41
16,Meghalaya,102,101,117,139,161,188,230,264,318,...,2320,2771,3432.71,3833.36,4770.19,5945.06,6123.40,6811.01,11893.17,9583.25
17,Mizoram,0,0,0,0,0,177,55,306,287,...,2295,2559,2868.54,3529.02,4139.50,5638.11,5335.50,5635.93,7523.22,7576.53
18,Nagaland,164,132,166,215,202,272,344,436,457,...,3085,3563,3949.46,4520.10,5576.04,6448.47,7194.14,7227.16,9241.40,10582.20
19,Odisha,877,814,1191,997,1281,1410,1730,1990,2261,...,19346,22844,30051.73,30540.64,36051.31,42105.10,47255.62,56130.92,76127.06,84487.77
20,Punjab,817,996,1122,1434,1726,1963,1829,2623,2666,...,26297,26519,28785.71,31307.95,37060.03,36810.32,44507.28,47656.37,56430.95,61813.86
21,Rajasthan,1120,1360,1419,1585,1838,2116,2557,3384,3415,...,31856,37757,42968.24,48749.81,53703.32,65372.08,81263.91,94101.08,125811.63,137713.39
22,Sikkim,43,45,47,67,76,104,115,139,164,...,2253,2820,2981.91,3509.84,3437.58,3943.73,3930.92,4469.04,6716.29,5525.73
23,Tamil Nadu,1686,2006,2292,2752,2950,3309,3612,4196,4617,...,51147,55748,67723.09,72730.33,90881.74,109465.27,121395.90,134192.38,161424.09,182338.58
24,Telangana,0,0,0,0,0,0,0,0,0,...,0,0,0.00,0.00,0.00,0.00,0.00,0.00,99957.97,115059.19
25,Tripura,143,124,145,188,204,259,300,393,492,...,3301,3835,4511.04,5757.51,5624.33,6437.75,7027.49,7825.38,12399.45,14948.92
26,Uttar Pradesh,2668,2942,3490,4116,5186,5331,6225,6901,8079,...,74983,87304,104398.11,121115.30,134585.83,153712.31,173720.21,200720.05,262302.82,292687.32
27,Uttarakhand,0,0,0,0,0,0,0,0,0,...,8516,9975,10888.79,13297.14,14009.97,16232.36,19216.41,21523.23,31455.80,31893.64
28,West Bengal,1552,1838,2072,2181,2738,2974,3508,3941,4279,...,41203,46644,60933.12,68134.03,72962.17,83830.88,95357.50,108513.39,129647.46,138374.00
29,Delhi,0,0,0,0,0,0,0,0,0,...,12966,18160,20361.30,24925.92,25524.32,26402.43,29858.81,34051.60,34790.00,41129.00
30,Puducherry,0,0,0,0,0,0,0,0,0,...,2387,2588,2956.60,3585.83,4060.98,3756.01,3556.17,5050.33,5917.99,6431.00

In [61]:
df8.to_csv('Aggregate_Expenditure.csv')

In [62]:
df8.shape

(31, 37)

In [63]:
df8['State']

0       Andhra Pradesh
1     Arunachal Pradesh
2                 Assam
3                 Bihar
4          Chhattisgarh
5                   Goa
6               Gujarat
7               Haryana
8      Himachal Pradesh
9       Jammu & Kashmir
10            Jharkhand
11            Karnataka
12               Kerala
13       Madhya Pradesh
14          Maharashtra
15              Manipur
16            Meghalaya
17              Mizoram
18             Nagaland
19               Odisha
20               Punjab
21            Rajasthan
22               Sikkim
23           Tamil Nadu
24            Telangana
25              Tripura
26        Uttar Pradesh
27          Uttarakhand
28          West Bengal
29                Delhi
30           Puducherry
Name: State, dtype: object

## Check for null values

In [64]:

df.isna().sum()

State           0
1980-81         0
1981-82         0
1982-83         0
1983-84         0
1984-85         0
1985-86         0
1986-87         0
1987-88         0
1988-89         0
1989-90         0
1990-91         0
1991-92         0
1992-93         0
1993-94         0
1994-95         0
1995-96         0
1996-97         0
1997-98         0
1998-99         0
1999-00         0
2000-01         0
2001-02         0
2002-03         0
2003-04         0
2004-05         0
2005-06         0
2006-07         0
2007-08         0
2008-09         0
2009-10         0
2010-11         0
2011-12         0
2012-13         0
2013-14         0
2014-15         0
2015-16 (RE)    0
dtype: int64

#  Describe the Data

In [67]:
df.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16 (RE)
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,217.870968,247.064516,301.709677,347.935484,400.612903,549.387097,632.645161,730.709677,838.612903,937.419355,...,7384.709677,8830.516129,11017.419355,13059.032258,14977.096774,17371.612903,19965.806452,22468.064516,32330.000000,34670.322581
std,243.967312,275.390261,336.773732,394.071815,453.919573,610.972431,719.735116,787.844663,902.880268,1050.380337,...,7302.923881,8600.814294,10953.995304,13018.444698,14981.074103,17292.829554,19844.016525,22423.256888,28543.398653,30915.513849
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2330.000000,2010.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,17.500000,59.000000,88.500000,115.000000,128.000000,...,1025.500000,1151.500000,1455.000000,1780.000000,2010.000000,2320.000000,2405.000000,2820.000000,6205.000000,5945.000000
50%,125.000000,134.000000,149.000000,179.000000,215.000000,273.000000,338.000000,460.000000,458.000000,514.000000,...,5220.000000,6947.000000,8870.000000,10040.000000,10810.000000,11190.000000,12560.000000,14510.000000,26670.000000,27810.000000
75%,394.000000,440.500000,522.500000,613.000000,708.000000,1028.000000,1193.500000,1435.000000,1515.500000,1630.000000,...,11853.500000,14249.000000,17260.000000,19725.000000,23120.000000,27490.000000,33535.000000,38665.000000,54360.000000,56795.000000
max,821.000000,847.000000,1031.000000,1282.000000,1434.000000,1968.000000,2480.000000,2603.000000,2937.000000,3610.000000,...,28276.000000,30006.000000,39510.000000,47360.000000,53830.000000,61130.000000,70030.000000,78200.000000,102240.000000,116170.000000

In [66]:
df2.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
count,31.000000,31.00000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,477.741935,550.83871,652.903226,767.838710,914.516129,1057.096774,1227.612903,1454.645161,1684.870968,1942.516129,...,16625.193548,19121.935484,22570.874194,26327.033226,30652.208065,35384.186452,40497.176774,45374.176774,59846.929355,64328.200323
std,545.056998,630.86539,750.580635,888.969557,1068.643653,1213.719362,1383.643612,1581.256010,1872.777718,2224.917105,...,16432.454810,18756.856000,22171.274225,25739.801421,30235.831407,34876.098072,39888.163996,44684.402510,52983.022316,57006.732779
min,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4895.440000,4258.510000
25%,0.000000,0.00000,0.000000,0.000000,0.000000,39.000000,118.500000,179.500000,206.500000,234.000000,...,2441.500000,2675.000000,3009.490000,3956.265000,4273.580000,4940.440000,5458.960000,5849.655000,9446.455000,9415.725000
50%,273.000000,296.00000,326.000000,422.000000,509.000000,595.000000,653.000000,861.000000,966.000000,1081.000000,...,11234.000000,12744.000000,14243.310000,17265.440000,20242.580000,22680.480000,26971.840000,31971.810000,48982.740000,52623.200000
75%,899.000000,1020.50000,1261.000000,1421.500000,1694.000000,2035.000000,2241.000000,2643.000000,3106.500000,3605.000000,...,23658.500000,27364.500000,31904.740000,38014.550000,44942.470000,53173.510000,63215.160000,72564.155000,98279.115000,99705.730000
max,1917.000000,2238.00000,2628.000000,3181.000000,3880.000000,4491.000000,4979.000000,5505.000000,6541.000000,7903.000000,...,61385.000000,65223.000000,75968.890000,94915.970000,107675.610000,123885.170000,140723.640000,158146.870000,194677.310000,215756.180000

In [68]:
df3.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16 (RE)
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,-47.935484,-44.500000,-28.654839,-6.796774,29.787097,-21.103226,-5.464516,35.096774,58.270968,118.783871,...,-943.580645,-1549.032258,-552.580645,796.774194,-430.322581,-901.290323,-816.129032,165.806452,391.612903,-1995.483871
std,57.927504,85.616389,82.661861,74.549945,98.654957,101.671623,118.140125,131.499393,154.035633,224.243308,...,2424.633880,3734.905295,3578.165235,5280.950916,4689.106869,4494.556516,4433.577696,5275.060678,8249.044024,7625.997132
min,-183.000000,-353.400000,-210.100000,-176.300000,-106.700000,-297.700000,-346.000000,-252.000000,-277.500000,-98.000000,...,-4901.000000,-14803.000000,-5580.000000,-7050.000000,-10640.000000,-9910.000000,-7460.000000,-10070.000000,-32410.000000,-34120.000000
25%,-92.500000,-71.300000,-49.650000,-48.200000,-30.400000,-65.600000,-54.000000,-32.500000,-24.050000,0.000000,...,-2379.500000,-3244.000000,-1865.000000,-1320.000000,-2910.000000,-3225.000000,-3030.000000,-1630.000000,-2370.000000,-4455.000000
50%,-36.000000,-7.800000,-9.100000,0.000000,0.000000,0.000000,-22.000000,0.000000,0.000000,34.000000,...,-810.000000,-904.000000,-630.000000,-260.000000,-250.000000,-930.000000,-1370.000000,-240.000000,-160.000000,-690.000000
75%,0.000000,0.000000,0.000000,0.000000,72.450000,1.850000,0.800000,95.500000,131.950000,141.850000,...,-210.000000,-162.500000,35.000000,2440.000000,440.000000,-145.000000,-60.000000,925.000000,4365.000000,-20.000000
max,28.000000,87.800000,242.400000,206.200000,371.900000,316.700000,309.000000,356.000000,604.500000,1031.000000,...,8333.000000,8147.000000,14710.000000,21580.000000,17270.000000,14570.000000,13820.000000,18920.000000,14240.000000,9560.000000

In [69]:
df4.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,213.483871,265.645161,306.032258,346.935484,395.483871,469.516129,539.129032,623.387097,722.677419,838.580645,...,8493.225806,9645.806452,10800.645161,12173.548387,15441.612903,18676.129032,21931.935484,23877.741935,27308.709677,31266.129032
std,282.378100,350.320191,408.258209,458.165468,515.619813,612.606174,702.862421,814.694285,948.907877,1101.269442,...,10119.320922,11630.809881,12875.830830,14401.253313,18385.380079,22059.128825,25813.565093,27599.278216,29387.557088,33167.884736
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,270.000000,330.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,4.500000,7.500000,6.500000,7.000000,...,455.000000,510.000000,585.000000,700.000000,1060.000000,1225.000000,1460.000000,1485.000000,3055.000000,3315.000000
50%,38.000000,60.000000,62.000000,71.000000,79.000000,104.000000,118.000000,123.000000,138.000000,142.000000,...,4030.000000,5090.000000,6170.000000,7120.000000,9010.000000,10710.000000,13030.000000,14340.000000,19270.000000,21280.000000
75%,367.500000,454.000000,524.500000,593.500000,667.500000,781.000000,894.000000,1020.000000,1202.000000,1405.500000,...,11655.000000,13205.000000,14680.000000,17085.000000,21275.000000,25550.000000,30540.000000,33515.000000,38835.000000,45965.000000
max,1130.000000,1384.000000,1648.000000,1823.000000,1966.000000,2377.000000,2792.000000,3219.000000,3823.000000,4401.000000,...,40100.000000,47530.000000,52030.000000,59110.000000,75030.000000,87610.000000,103450.000000,108600.000000,118960.000000,130580.000000

In [70]:
df5.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,Unnamed: 37
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,3.100000e+01,3.100000e+01,3.100000e+01,3.100000e+01,3.100000e+01,3.100000e+01,31.0
mean,3695.677419,4251.903226,4729.709677,5518.741935,6092.838710,6851.870968,7561.451613,8652.096774,10335.645161,11862.258065,...,140244.935484,161659.290323,185930.225806,2.225549e+05,2.776474e+05,3.160647e+05,3.595234e+05,4.011273e+05,2.251203e+05,0.0
std,4626.159483,5232.534035,5821.425605,6715.995488,7420.280107,8393.130436,9211.628824,10665.139588,12681.491433,14813.328172,...,151460.084292,169777.916491,195463.847485,2.358520e+05,2.902412e+05,3.317049e+05,3.787365e+05,4.181877e+05,3.662511e+05,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2506.000000,3229.000000,5260.000000,6.388000e+03,7.258690e+03,8.361930e+03,1.029337e+04,1.155933e+04,0.000000e+00,0.0
25%,87.500000,110.000000,126.500000,147.500000,178.000000,225.000000,259.500000,308.000000,337.500000,362.000000,...,15681.000000,19493.500000,22264.500000,2.573650e+04,3.108524e+04,3.025966e+04,3.391814e+04,3.760708e+04,0.000000e+00,0.0
50%,1186.000000,1361.000000,1561.000000,1782.000000,2021.000000,2256.000000,2620.000000,2524.000000,3065.000000,3299.000000,...,113680.000000,142279.000000,162923.000000,1.975300e+05,2.252835e+05,2.552726e+05,2.772707e+05,3.098072e+05,0.000000e+00,0.0
75%,6781.500000,7865.500000,8823.500000,10277.500000,11351.000000,12740.000000,13892.000000,15748.500000,19445.000000,21412.000000,...,184981.500000,216866.000000,248912.000000,2.918810e+05,3.716388e+05,4.116369e+05,4.667669e+05,5.298482e+05,3.729162e+05,0.0
max,16631.000000,18738.000000,20315.000000,23457.000000,25558.000000,29616.000000,32009.000000,37754.000000,45160.000000,55674.000000,...,684817.000000,753969.000000,855751.000000,1.049150e+06,1.272967e+06,1.448466e+06,1.647506e+06,1.792122e+06,1.212668e+06,0.0

In [71]:
df6.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,119.748387,131.054839,160.841935,205.122581,264.506452,242.580645,299.000000,361.951613,376.516129,497.870968,...,2527.096774,2510.322581,4444.516129,6223.870968,5208.064516,5539.354839,6386.774194,8138.709677,11818.064516,10785.483871
std,157.535761,151.383819,181.661538,251.547921,344.410572,312.861607,364.210104,371.148541,434.430115,584.607147,...,3469.690854,3711.020061,5303.088936,7249.748813,6373.230693,6362.278908,6843.851931,8504.894176,10812.060371,9997.761362
min,-34.900000,0.000000,-1.800000,0.000000,-4.600000,-12.000000,-22.000000,0.000000,0.000000,-3.000000,...,-1180.000000,-2820.000000,-1410.000000,-70.000000,-730.000000,-620.000000,-340.000000,-270.000000,350.000000,110.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,13.000000,10.500000,30.500000,...,90.000000,95.000000,335.000000,655.000000,455.000000,850.000000,490.000000,1050.000000,1870.000000,1550.000000
50%,5.600000,61.700000,122.900000,133.700000,232.300000,154.000000,170.000000,216.000000,289.000000,393.000000,...,890.000000,1260.000000,2330.000000,2780.000000,1990.000000,1930.000000,2980.000000,4550.000000,9140.000000,6840.000000
75%,216.250000,225.000000,277.400000,327.600000,396.800000,354.000000,464.000000,614.000000,616.500000,816.000000,...,4175.000000,4145.000000,6830.000000,10195.000000,7495.000000,9760.000000,12050.000000,16065.000000,18705.000000,17275.000000
max,551.400000,488.500000,581.700000,1082.300000,1493.600000,1234.000000,1410.000000,1014.000000,1802.000000,2482.000000,...,11550.000000,13790.000000,20510.000000,26160.000000,19530.000000,19970.000000,19240.000000,26020.000000,37250.000000,31830.000000

In [73]:
df7.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,253.419355,261.129032,274.354839,314.129032,371.258065,390.258065,442.838710,476.870968,479.032258,534.451613,...,5072.709677,5815.967742,6752.657097,7345.272258,7680.535161,9226.217419,10072.813548,10889.440000,14450.423871,16075.496452
std,275.637899,293.882487,313.847792,365.928658,441.949316,427.046443,478.737026,498.235135,496.527172,555.215204,...,5083.816311,5827.726077,6993.437091,7570.657703,7586.203506,9396.565431,9725.493151,11135.915215,14628.949628,15974.010573
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,862.770000,832.670000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,13.000000,51.000000,67.000000,70.500000,78.000000,...,876.000000,1016.000000,1391.250000,1540.800000,1639.995000,1743.045000,1634.710000,1676.615000,3528.045000,4212.340000
50%,154.000000,211.000000,178.000000,198.000000,238.000000,264.000000,336.000000,375.000000,420.000000,419.000000,...,3276.000000,4189.000000,4329.620000,4701.120000,6100.450000,6092.650000,7001.990000,6582.370000,9313.920000,12039.320000
75%,434.500000,485.500000,457.500000,566.000000,688.500000,683.500000,814.000000,849.000000,824.500000,915.000000,...,7397.500000,8509.500000,8996.215000,10618.450000,11815.595000,12699.660000,16271.275000,18259.715000,23453.650000,25179.265000
max,952.000000,1036.000000,1127.000000,1355.000000,1894.000000,1629.000000,1876.000000,1821.000000,1822.000000,1983.000000,...,19284.000000,22081.000000,28429.220000,31741.700000,26910.220000,29827.140000,32996.570000,42573.180000,70712.590000,76931.140000

In [74]:
df8.describe()

,1980-81,1981-82,1982-83,1983-84,1984-85,1985-86,1986-87,1987-88,1988-89,1989-90,...,2006-07,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15 (RE),2015-16 (BE)
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,...,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,731.129032,812.000000,927.193548,1081.967742,1285.741935,1447.225806,1670.483871,1931.451613,2163.838710,2476.870968,...,21697.838710,24937.709677,29323.531290,33672.305484,38332.743226,44610.403871,50569.990323,56263.616774,74297.353226,80403.696774
std,805.730838,917.489909,1056.255790,1241.267188,1486.659521,1624.329948,1848.081291,2059.903911,2359.726341,2768.606939,...,21303.500201,24303.197162,28888.023562,32835.793548,37429.091394,43606.610182,49106.767701,55400.535815,66361.309812,72053.393072
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5917.990000,5525.730000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,52.000000,172.500000,261.000000,285.500000,315.000000,...,3238.500000,3641.500000,4457.405000,5380.535000,5869.600000,6763.905000,7110.815000,7803.505000,12146.310000,14025.845000
50%,428.000000,548.000000,504.000000,620.000000,747.000000,889.000000,989.000000,1269.000000,1404.000000,1611.000000,...,13873.000000,18160.000000,20361.300000,24925.920000,25946.970000,29856.230000,33747.640000,37178.400000,56430.950000,63602.170000
75%,1372.000000,1487.000000,1836.000000,2073.000000,2435.500000,2759.500000,3196.000000,3675.500000,4028.500000,4612.000000,...,31036.500000,36511.000000,41499.250000,49391.130000,56879.250000,72393.135000,82380.615000,91932.620000,124439.910000,128328.695000
max,2668.000000,3088.000000,3585.000000,4244.000000,5186.000000,5732.000000,6412.000000,6929.000000,8102.000000,9737.000000,...,75841.000000,87304.000000,104398.110000,121115.300000,134585.830000,153712.310000,173720.210000,200720.050000,262302.820000,292687.320000